/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using meridian.bewell.controller;
using System.Linq;
using meridian.bewell.proto;

namespace bewell.Areas.Admin.Controllers
{
    public partial class admin_commentsController : meridian_comments
	{
        public admin_commentsController()
		{
		}

        protected override IQueryable<comments> Filter(IQueryable<comments> _src)
        {
            if(Request["type"]!=null)
            {
               string type =  Request["type"] as string;
                switch (type)
                {
                    case "hotel":
                        {
                            _src = _src.Where(c => c.proto_name == "hotels");
                            break;
                        }
                    case "resort":
                        {
                            _src = _src.Where(c => c.proto_name == "resorts");
                            break;
                        }
                }
            }
            return base.Filter(_src);
        }
	}
}
