/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using meridian.bewell.controller;

namespace bewell.Areas.Admin.Controllers
{
	public partial class admin_resort_zonesController : meridian_resort_zones
	{
		public admin_resort_zonesController()
		{
		}
	}
}
