/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;
using meridian.bewell.controller;
using MySql.Data.MySqlClient;
using meridian.bewell;
using meridian.bewell.system;
using meridian.bewell.proto;
using admin.web.common;

namespace bewell.Areas.Admin.Controllers
{
	public partial class admin_questionsController : meridian_questions
	{
		public admin_questionsController()
		{
		}
	}
}
