/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using meridian.bewell.controller;

namespace bewell.Areas.Admin.Controllers
{
	public partial class admin_territoriesController : meridian_territories
	{
		public admin_territoriesController()
		{
		}
	}
}
