/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using meridian.bewell.controller;

namespace bewell.Areas.Admin.Controllers
{
	public partial class admin_treatment_optionsController : meridian_treatment_options
	{
		public admin_treatment_optionsController()
		{
		}
	}
}
