/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using meridian.bewell.controller;

namespace bewell.Areas.Admin.Controllers
{
	public partial class admin_health_factorsController : meridian_health_factors
	{
		public admin_health_factorsController()
		{
		}
	}
}
