/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System.Collections.Generic;
using System.Linq;
using Apache.NMS;
using meridian.bewell.controller;
using meridian.bewell.proto;
using meridian.bewell.system;

namespace bewell.Areas.Admin.Controllers
{
	public partial class admin_hotelsController : meridian_hotels
	{
        public admin_hotelsController()
		{
		}
	}
}
