/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Script.Serialization;
using MySql.Data.MySqlClient;
using meridian.bewell;
using meridian.bewell.system;

namespace meridian.bewell.proto
{
	[MetadataType(typeof(accounts_sna_meta))]	public partial class accounts_sna : admin.db.IDatabaseEntity
	{
		public accounts_sna()
		{
		}
		private long m_id = 0;
		internal bool mc_id { get; private set; }
		private string m_email = "";
		internal bool mc_email { get; private set; }
		private string m_facebook_id = "";
		internal bool mc_facebook_id { get; private set; }
		private string m_vk_id = "";
		internal bool mc_vk_id { get; private set; }
		private string m_google_id = "";
		internal bool mc_google_id { get; private set; }
		private string m_odnoklassniki_id = "";
		internal bool mc_odnoklassniki_id { get; private set; }
		public void LoadFromReader(MySqlDataReader _reader)
		{
			m_id = _reader["id"].GetType() != typeof(System.DBNull) ? _reader.GetInt64("id") : 0;
			mc_id = false;
			m_email = _reader["email"].GetType() != typeof(System.DBNull) ? _reader.GetString("email") : "";
			mc_email = false;
			m_facebook_id = _reader["facebook_id"].GetType() != typeof(System.DBNull) ? _reader.GetString("facebook_id") : "";
			mc_facebook_id = false;
			m_vk_id = _reader["vk_id"].GetType() != typeof(System.DBNull) ? _reader.GetString("vk_id") : "";
			mc_vk_id = false;
			m_google_id = _reader["google_id"].GetType() != typeof(System.DBNull) ? _reader.GetString("google_id") : "";
			mc_google_id = false;
			m_odnoklassniki_id = _reader["odnoklassniki_id"].GetType() != typeof(System.DBNull) ? _reader.GetString("odnoklassniki_id") : "";
			mc_odnoklassniki_id = false;
		}
		public void LoadAggregations(Meridian _meridian)
		{
		}
		public void DeleteAggregations()
		{
		}
		public void LoadCompositions(Meridian _meridian)
		{
			string[] keyIds = null;
		}
		public void SaveCompositions(Meridian _meridian)
		{
		}
		public void DeleteCompositions(Meridian _meridian)
		{
			string[] keyIds = null;
		}
		public string ProtoName
		{
			get { return "accounts_sna"; }
		}
		/* metafile template 
		internal class accounts_sna_meta
		{
			public long id { get; set; }
			public string email { get; set; }
			public string facebook_id { get; set; }
			public string vk_id { get; set; }
			public string google_id { get; set; }
			public string odnoklassniki_id { get; set; }
		}
		 metafile template */
		public long id
		{
			get
			{
				return m_id;
			}
			set
			{
				if(m_id != value)
				{
					m_id = value != null ? value : 0;
					mc_id = true;
					// call update worker thread;
				}
			}
		}
		public string email
		{
			get
			{
				return m_email;
			}
			set
			{
				if(m_email != value)
				{
					m_email = value != null ? value : "";
					mc_email = true;
					// call update worker thread;
				}
			}
		}
		public string facebook_id
		{
			get
			{
				return m_facebook_id;
			}
			set
			{
				if(m_facebook_id != value)
				{
					m_facebook_id = value != null ? value : "";
					mc_facebook_id = true;
					// call update worker thread;
				}
			}
		}
		public string vk_id
		{
			get
			{
				return m_vk_id;
			}
			set
			{
				if(m_vk_id != value)
				{
					m_vk_id = value != null ? value : "";
					mc_vk_id = true;
					// call update worker thread;
				}
			}
		}
		public string google_id
		{
			get
			{
				return m_google_id;
			}
			set
			{
				if(m_google_id != value)
				{
					m_google_id = value != null ? value : "";
					mc_google_id = true;
					// call update worker thread;
				}
			}
		}
		public string odnoklassniki_id
		{
			get
			{
				return m_odnoklassniki_id;
			}
			set
			{
				if(m_odnoklassniki_id != value)
				{
					m_odnoklassniki_id = value != null ? value : "";
					mc_odnoklassniki_id = true;
					// call update worker thread;
				}
			}
		}
	}
}
