/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Script.Serialization;
using MySql.Data.MySqlClient;
using meridian.bewell;
using meridian.bewell.system;

namespace meridian.bewell.proto
{
	[MetadataType(typeof(citations_meta))]	public partial class citations : admin.db.IDatabaseEntity
	{
		public citations()
		{
		}
		private long m_id = 0;
		internal bool mc_id { get; private set; }
		private string m_author = "";
		internal bool mc_author { get; private set; }
		private string m_text = "";
		internal bool mc_text { get; private set; }
		private string m_picture = "";
		internal bool mc_picture { get; private set; }
		public void LoadFromReader(MySqlDataReader _reader)
		{
			m_id = _reader["id"].GetType() != typeof(System.DBNull) ? _reader.GetInt64("id") : 0;
			mc_id = false;
			m_author = _reader["author"].GetType() != typeof(System.DBNull) ? _reader.GetString("author") : "";
			mc_author = false;
			m_text = _reader["text"].GetType() != typeof(System.DBNull) ? _reader.GetString("text") : "";
			mc_text = false;
			m_picture = _reader["picture"].GetType() != typeof(System.DBNull) ? _reader.GetString("picture") : "";
			mc_picture = false;
		}
		public void LoadAggregations(Meridian _meridian)
		{
		}
		public void DeleteAggregations()
		{
		}
		public void LoadCompositions(Meridian _meridian)
		{
			string[] keyIds = null;
		}
		public void SaveCompositions(Meridian _meridian)
		{
		}
		public void DeleteCompositions(Meridian _meridian)
		{
			string[] keyIds = null;
		}
		public string ProtoName
		{
			get { return "citations"; }
		}
		/* metafile template 
		internal class citations_meta
		{
			public long id { get; set; }
			public string author { get; set; }
			public string text { get; set; }
			public string picture { get; set; }
		}
		 metafile template */
		public long id
		{
			get
			{
				return m_id;
			}
			set
			{
				if(m_id != value)
				{
					m_id = value != null ? value : 0;
					mc_id = true;
					// call update worker thread;
				}
			}
		}
		public string author
		{
			get
			{
				return m_author;
			}
			set
			{
				if(m_author != value)
				{
					m_author = value != null ? value : "";
					mc_author = true;
					// call update worker thread;
				}
			}
		}
		public string text
		{
			get
			{
				return m_text;
			}
			set
			{
				if(m_text != value)
				{
					m_text = value != null ? value : "";
					mc_text = true;
					// call update worker thread;
				}
			}
		}
		public string picture
		{
			get
			{
				return m_picture;
			}
			set
			{
				if(m_picture != value)
				{
					m_picture = value != null ? value : "";
					mc_picture = true;
					// call update worker thread;
				}
			}
		}
	}
}
