/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Script.Serialization;
using MySql.Data.MySqlClient;
using meridian.bewell;
using meridian.bewell.system;

namespace meridian.bewell.proto
{
	[MetadataType(typeof(countries_meta))]	public partial class countries : admin.db.IDatabaseEntity
	{
		public countries()
		{
		}
		private long m_id = 0;
		internal bool mc_id { get; private set; }
		private string m_title = "";
		internal bool mc_title { get; private set; }
		private long m_territory_id = 0;
		internal bool mc_territory_id { get; private set; }
		private string m_health_factors = "";
		internal bool mc_health_factors { get; private set; }
		public void LoadFromReader(MySqlDataReader _reader)
		{
			m_id = _reader["id"].GetType() != typeof(System.DBNull) ? _reader.GetInt64("id") : 0;
			mc_id = false;
			m_title = _reader["title"].GetType() != typeof(System.DBNull) ? _reader.GetString("title") : "";
			mc_title = false;
			m_territory_id = _reader["territory_id"].GetType() != typeof(System.DBNull) ? _reader.GetInt64("territory_id") : 0;
			mc_territory_id = false;
			m_health_factors = _reader["health_factors"].GetType() != typeof(System.DBNull) ? _reader.GetString("health_factors") : "";
			mc_health_factors = false;
		}
		public void LoadAggregations(Meridian _meridian)
		{
		}
		public void DeleteAggregations()
		{
		}
		public void LoadCompositions(Meridian _meridian)
		{
			string[] keyIds = null;
		}
		public void SaveCompositions(Meridian _meridian)
		{
		}
		public void DeleteCompositions(Meridian _meridian)
		{
			string[] keyIds = null;
		}
		public string ProtoName
		{
			get { return "countries"; }
		}
		/* metafile template 
		internal class countries_meta
		{
			public long id { get; set; }
			public string title { get; set; }
			public long territory_id { get; set; }
			public string health_factors { get; set; }
		}
		 metafile template */
		public long id
		{
			get
			{
				return m_id;
			}
			set
			{
				if(m_id != value)
				{
					m_id = value != null ? value : 0;
					mc_id = true;
					// call update worker thread;
				}
			}
		}
		public string title
		{
			get
			{
				return m_title;
			}
			set
			{
				if(m_title != value)
				{
					m_title = value != null ? value : "";
					mc_title = true;
					// call update worker thread;
				}
			}
		}
		public long territory_id
		{
			get
			{
				return m_territory_id;
			}
			set
			{
				if(m_territory_id != value)
				{
					m_territory_id = value != null ? value : 0;
					mc_territory_id = true;
					// call update worker thread;
				}
			}
		}
		public string health_factors
		{
			get
			{
				return m_health_factors;
			}
			set
			{
				if(m_health_factors != value)
				{
					m_health_factors = value != null ? value : "";
					mc_health_factors = true;
					// call update worker thread;
				}
			}
		}
	}
}
