/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Script.Serialization;
using MySql.Data.MySqlClient;
using meridian.bewell;
using meridian.bewell.system;

namespace meridian.bewell.proto
{
	[MetadataType(typeof(entity_photos_meta))]	public partial class entity_photos : admin.db.IDatabaseEntity
	{
		public entity_photos()
		{
		}
		private long m_id = 0;
		internal bool mc_id { get; private set; }
		private long m_entity_id = 0;
		internal bool mc_entity_id { get; private set; }
		private string m_proto_name = "";
		internal bool mc_proto_name { get; private set; }
		private string m_guid = "";
		internal bool mc_guid { get; private set; }
		private string m_original = "";
		internal bool mc_original { get; private set; }
		private string m_thumbnail_small = "";
		internal bool mc_thumbnail_small { get; private set; }
		private string m_thumbnail_mid = "";
		internal bool mc_thumbnail_mid { get; private set; }
		private string m_thumbnail_large = "";
		internal bool mc_thumbnail_large { get; private set; }
		private bool m_is_main = false;
		internal bool mc_is_main { get; private set; }
		private int m_order_number = 0;
		internal bool mc_order_number { get; private set; }
		public void LoadFromReader(MySqlDataReader _reader)
		{
			m_id = _reader["id"].GetType() != typeof(System.DBNull) ? _reader.GetInt64("id") : 0;
			mc_id = false;
			m_entity_id = _reader["entity_id"].GetType() != typeof(System.DBNull) ? _reader.GetInt64("entity_id") : 0;
			mc_entity_id = false;
			m_proto_name = _reader["proto_name"].GetType() != typeof(System.DBNull) ? _reader.GetString("proto_name") : "";
			mc_proto_name = false;
			m_guid = _reader["guid"].GetType() != typeof(System.DBNull) ? _reader.GetString("guid") : "";
			mc_guid = false;
			m_original = _reader["original"].GetType() != typeof(System.DBNull) ? _reader.GetString("original") : "";
			mc_original = false;
			m_thumbnail_small = _reader["thumbnail_small"].GetType() != typeof(System.DBNull) ? _reader.GetString("thumbnail_small") : "";
			mc_thumbnail_small = false;
			m_thumbnail_mid = _reader["thumbnail_mid"].GetType() != typeof(System.DBNull) ? _reader.GetString("thumbnail_mid") : "";
			mc_thumbnail_mid = false;
			m_thumbnail_large = _reader["thumbnail_large"].GetType() != typeof(System.DBNull) ? _reader.GetString("thumbnail_large") : "";
			mc_thumbnail_large = false;
			m_is_main = _reader["is_main"].GetType() != typeof(System.DBNull) ? _reader.GetBoolean("is_main") : false;
			mc_is_main = false;
			m_order_number = _reader["order_number"].GetType() != typeof(System.DBNull) ? _reader.GetInt32("order_number") : 0;
			mc_order_number = false;
		}
		public void LoadAggregations(Meridian _meridian)
		{
		}
		public void DeleteAggregations()
		{
		}
		public void LoadCompositions(Meridian _meridian)
		{
			string[] keyIds = null;
		}
		public void SaveCompositions(Meridian _meridian)
		{
		}
		public void DeleteCompositions(Meridian _meridian)
		{
			string[] keyIds = null;
		}
		public string ProtoName
		{
			get { return "entity_photos"; }
		}
		/* metafile template 
		internal class entity_photos_meta
		{
			public long id { get; set; }
			public long entity_id { get; set; }
			public string proto_name { get; set; }
			public string guid { get; set; }
			public string original { get; set; }
			public string thumbnail_small { get; set; }
			public string thumbnail_mid { get; set; }
			public string thumbnail_large { get; set; }
			public bool is_main { get; set; }
			public int order_number { get; set; }
		}
		 metafile template */
		public long id
		{
			get
			{
				return m_id;
			}
			set
			{
				if(m_id != value)
				{
					m_id = value != null ? value : 0;
					mc_id = true;
					// call update worker thread;
				}
			}
		}
		public long entity_id
		{
			get
			{
				return m_entity_id;
			}
			set
			{
				if(m_entity_id != value)
				{
					m_entity_id = value != null ? value : 0;
					mc_entity_id = true;
					// call update worker thread;
				}
			}
		}
		public string proto_name
		{
			get
			{
				return m_proto_name;
			}
			set
			{
				if(m_proto_name != value)
				{
					m_proto_name = value != null ? value : "";
					mc_proto_name = true;
					// call update worker thread;
				}
			}
		}
		public string guid
		{
			get
			{
				return m_guid;
			}
			set
			{
				if(m_guid != value)
				{
					m_guid = value != null ? value : "";
					mc_guid = true;
					// call update worker thread;
				}
			}
		}
		public string original
		{
			get
			{
				return m_original;
			}
			set
			{
				if(m_original != value)
				{
					m_original = value != null ? value : "";
					mc_original = true;
					// call update worker thread;
				}
			}
		}
		public string thumbnail_small
		{
			get
			{
				return m_thumbnail_small;
			}
			set
			{
				if(m_thumbnail_small != value)
				{
					m_thumbnail_small = value != null ? value : "";
					mc_thumbnail_small = true;
					// call update worker thread;
				}
			}
		}
		public string thumbnail_mid
		{
			get
			{
				return m_thumbnail_mid;
			}
			set
			{
				if(m_thumbnail_mid != value)
				{
					m_thumbnail_mid = value != null ? value : "";
					mc_thumbnail_mid = true;
					// call update worker thread;
				}
			}
		}
		public string thumbnail_large
		{
			get
			{
				return m_thumbnail_large;
			}
			set
			{
				if(m_thumbnail_large != value)
				{
					m_thumbnail_large = value != null ? value : "";
					mc_thumbnail_large = true;
					// call update worker thread;
				}
			}
		}
		public bool is_main
		{
			get
			{
				return m_is_main;
			}
			set
			{
				if(m_is_main != value)
				{
					m_is_main = value != null ? value : false;
					mc_is_main = true;
					// call update worker thread;
				}
			}
		}
		public int order_number
		{
			get
			{
				return m_order_number;
			}
			set
			{
				if(m_order_number != value)
				{
					m_order_number = value != null ? value : 0;
					mc_order_number = true;
					// call update worker thread;
				}
			}
		}
	}
}
