/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Script.Serialization;
using MySql.Data.MySqlClient;
using meridian.bewell;
using meridian.bewell.system;

namespace meridian.bewell.proto
{
	[MetadataType(typeof(field_values_meta))]	public partial class field_values : admin.db.IDatabaseEntity
	{
		public field_values()
		{
		}
		private long m_id = 0;
		internal bool mc_id { get; private set; }
		private long m_entity_id = 0;
		internal bool mc_entity_id { get; private set; }
		private string m_proto_name = "";
		internal bool mc_proto_name { get; private set; }
		private long m_field_id = 0;
		internal bool mc_field_id { get; private set; }
		private string m_field_value = "";
		internal bool mc_field_value { get; private set; }
		public void LoadFromReader(MySqlDataReader _reader)
		{
			m_id = _reader["id"].GetType() != typeof(System.DBNull) ? _reader.GetInt64("id") : 0;
			mc_id = false;
			m_entity_id = _reader["entity_id"].GetType() != typeof(System.DBNull) ? _reader.GetInt64("entity_id") : 0;
			mc_entity_id = false;
			m_proto_name = _reader["proto_name"].GetType() != typeof(System.DBNull) ? _reader.GetString("proto_name") : "";
			mc_proto_name = false;
			m_field_id = _reader["field_id"].GetType() != typeof(System.DBNull) ? _reader.GetInt64("field_id") : 0;
			mc_field_id = false;
			m_field_value = _reader["field_value"].GetType() != typeof(System.DBNull) ? _reader.GetString("field_value") : "";
			mc_field_value = false;
		}
		public void LoadAggregations(Meridian _meridian)
		{
			if((field_id > 0) && (_meridian.entity_fieldsStore.Exists(field_id)))
			{
				this.fv_entity_fields_entity_fields = _meridian.entity_fieldsStore.Get(field_id);;
				this.fv_entity_fields_entity_fields.AddFieldValues(this);
			}
		}
		public void DeleteAggregations()
		{
			if(this.fv_entity_fields_entity_fields != null)
			{
				this.fv_entity_fields_entity_fields.RemoveFieldValues(this);
			}
		}
		public void LoadCompositions(Meridian _meridian)
		{
			string[] keyIds = null;
		}
		public void SaveCompositions(Meridian _meridian)
		{
		}
		public void DeleteCompositions(Meridian _meridian)
		{
			string[] keyIds = null;
		}
		public string ProtoName
		{
			get { return "field_values"; }
		}
		/* metafile template 
		internal class field_values_meta
		{
			public long id { get; set; }
			public long entity_id { get; set; }
			public string proto_name { get; set; }
			public long field_id { get; set; }
			public string field_value { get; set; }
		}
		 metafile template */
		public long id
		{
			get
			{
				return m_id;
			}
			set
			{
				if(m_id != value)
				{
					m_id = value != null ? value : 0;
					mc_id = true;
					// call update worker thread;
				}
			}
		}
		public long entity_id
		{
			get
			{
				return m_entity_id;
			}
			set
			{
				if(m_entity_id != value)
				{
					m_entity_id = value != null ? value : 0;
					mc_entity_id = true;
					// call update worker thread;
				}
			}
		}
		public string proto_name
		{
			get
			{
				return m_proto_name;
			}
			set
			{
				if(m_proto_name != value)
				{
					m_proto_name = value != null ? value : "";
					mc_proto_name = true;
					// call update worker thread;
				}
			}
		}
		public long field_id
		{
			get
			{
				return m_field_id;
			}
			set
			{
				if(m_field_id != value)
				{
					m_field_id = value != null ? value : 0;
					mc_field_id = true;
					// call update worker thread;
				}
			}
		}
		public string field_value
		{
			get
			{
				return m_field_value;
			}
			set
			{
				if(m_field_value != value)
				{
					m_field_value = value != null ? value : "";
					mc_field_value = true;
					// call update worker thread;
				}
			}
		}
		private entity_fields fv_entity_fields_entity_fields
		{
			get; set; 
		}
		public entity_fields GetFieldValuesEntity_field()
		{
			return fv_entity_fields_entity_fields ;
		}
	}
}
