/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Script.Serialization;
using MySql.Data.MySqlClient;
using meridian.bewell;
using meridian.bewell.system;

namespace meridian.bewell.proto
{
	[MetadataType(typeof(fieldset_fields_order_meta))]	public partial class fieldset_fields_order : admin.db.IDatabaseEntity
	{
		public fieldset_fields_order()
		{
		}
		private long m_id = 0;
		internal bool mc_id { get; private set; }
		private long m_fieldset_id = 0;
		internal bool mc_fieldset_id { get; private set; }
		private long m_field_id = 0;
		internal bool mc_field_id { get; private set; }
		private int m_order_number = 0;
		internal bool mc_order_number { get; private set; }
		public void LoadFromReader(MySqlDataReader _reader)
		{
			m_id = _reader["id"].GetType() != typeof(System.DBNull) ? _reader.GetInt64("id") : 0;
			mc_id = false;
			m_fieldset_id = _reader["fieldset_id"].GetType() != typeof(System.DBNull) ? _reader.GetInt64("fieldset_id") : 0;
			mc_fieldset_id = false;
			m_field_id = _reader["field_id"].GetType() != typeof(System.DBNull) ? _reader.GetInt64("field_id") : 0;
			mc_field_id = false;
			m_order_number = _reader["order_number"].GetType() != typeof(System.DBNull) ? _reader.GetInt32("order_number") : 0;
			mc_order_number = false;
		}
		public void LoadAggregations(Meridian _meridian)
		{
		}
		public void DeleteAggregations()
		{
		}
		public void LoadCompositions(Meridian _meridian)
		{
			string[] keyIds = null;
		}
		public void SaveCompositions(Meridian _meridian)
		{
		}
		public void DeleteCompositions(Meridian _meridian)
		{
			string[] keyIds = null;
		}
		public string ProtoName
		{
			get { return "fieldset_fields_order"; }
		}
		/* metafile template 
		internal class fieldset_fields_order_meta
		{
			public long id { get; set; }
			public long fieldset_id { get; set; }
			public long field_id { get; set; }
			public int order_number { get; set; }
		}
		 metafile template */
		public long id
		{
			get
			{
				return m_id;
			}
			set
			{
				if(m_id != value)
				{
					m_id = value != null ? value : 0;
					mc_id = true;
					// call update worker thread;
				}
			}
		}
		public long fieldset_id
		{
			get
			{
				return m_fieldset_id;
			}
			set
			{
				if(m_fieldset_id != value)
				{
					m_fieldset_id = value != null ? value : 0;
					mc_fieldset_id = true;
					// call update worker thread;
				}
			}
		}
		public long field_id
		{
			get
			{
				return m_field_id;
			}
			set
			{
				if(m_field_id != value)
				{
					m_field_id = value != null ? value : 0;
					mc_field_id = true;
					// call update worker thread;
				}
			}
		}
		public int order_number
		{
			get
			{
				return m_order_number;
			}
			set
			{
				if(m_order_number != value)
				{
					m_order_number = value != null ? value : 0;
					mc_order_number = true;
					// call update worker thread;
				}
			}
		}
	}
}
