/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Script.Serialization;
using MySql.Data.MySqlClient;
using meridian.bewell;
using meridian.bewell.system;

namespace meridian.bewell.proto
{
	[MetadataType(typeof(properties_meta))]	public partial class properties : admin.db.IDatabaseEntity
	{
		public properties()
		{
			properties_items = new List<hotels>();
		}
		private long m_id = 0;
		internal bool mc_id { get; private set; }
		private string m_title = "";
		internal bool mc_title { get; private set; }
		private long m_category_id = 0;
		internal bool mc_category_id { get; private set; }
		private long m_parent_id = 0;
		internal bool mc_parent_id { get; private set; }
		public void LoadFromReader(MySqlDataReader _reader)
		{
			m_id = _reader["id"].GetType() != typeof(System.DBNull) ? _reader.GetInt64("id") : 0;
			mc_id = false;
			m_title = _reader["title"].GetType() != typeof(System.DBNull) ? _reader.GetString("title") : "";
			mc_title = false;
			m_category_id = _reader["category_id"].GetType() != typeof(System.DBNull) ? _reader.GetInt64("category_id") : 0;
			mc_category_id = false;
			m_parent_id = _reader["parent_id"].GetType() != typeof(System.DBNull) ? _reader.GetInt64("parent_id") : 0;
			mc_parent_id = false;
		}
		public void LoadAggregations(Meridian _meridian)
		{
			if((category_id > 0) && (_meridian.property_categoriesStore.Exists(category_id)))
			{
				this.category_properties_property_categories = _meridian.property_categoriesStore.Get(category_id);;
				this.category_properties_property_categories.AddProperties(this);
			}
		}
		public void DeleteAggregations()
		{
			if(this.category_properties_property_categories != null)
			{
				this.category_properties_property_categories.RemoveProperties(this);
			}
		}
		public void LoadCompositions(Meridian _meridian)
		{
			string[] keyIds = null;
		}
		public void SaveCompositions(Meridian _meridian)
		{
		}
		public void DeleteCompositions(Meridian _meridian)
		{
			string[] keyIds = null;
		}
		public string ProtoName
		{
			get { return "properties"; }
		}
		/* metafile template 
		internal class properties_meta
		{
			public long id { get; set; }
			public string title { get; set; }
			public long category_id { get; set; }
			public long parent_id { get; set; }
		}
		 metafile template */
		public long id
		{
			get
			{
				return m_id;
			}
			set
			{
				if(m_id != value)
				{
					m_id = value != null ? value : 0;
					mc_id = true;
					// call update worker thread;
				}
			}
		}
		public string title
		{
			get
			{
				return m_title;
			}
			set
			{
				if(m_title != value)
				{
					m_title = value != null ? value : "";
					mc_title = true;
					// call update worker thread;
				}
			}
		}
		public long category_id
		{
			get
			{
				return m_category_id;
			}
			set
			{
				if(m_category_id != value)
				{
					m_category_id = value != null ? value : 0;
					mc_category_id = true;
					// call update worker thread;
				}
			}
		}
		public long parent_id
		{
			get
			{
				return m_parent_id;
			}
			set
			{
				if(m_parent_id != value)
				{
					m_parent_id = value != null ? value : 0;
					mc_parent_id = true;
					// call update worker thread;
				}
			}
		}
		private property_categories category_properties_property_categories
		{
			get; set; 
		}
		public property_categories GetPropertiesProperty_categorie()
		{
			return category_properties_property_categories ;
		}
		[ScriptIgnore]
		[ScaffoldColumn(false)]
		public List<hotels> properties_items
		{
			get; set; 
		}
		public void add_hotels_item(long id)
		{
			if (Meridian.Default.hotelsStore.Exists(id))
			{
				if (!properties_items.Any(s => s.id.Equals(id)))
				{
					properties_items.Add(Meridian.Default.hotelsStore.Get(id));
					SaveCompositions(Meridian.Default);
				}
			}
		}
		public void remove_hotels_item(long id)
		{
			if (properties_items.Any(s => s.id.Equals(id)))
			{
				properties_items.Remove(properties_items.Single(s => s.id.Equals(id)));;
				SaveCompositions(Meridian.Default);
			}
		}
	}
}
