/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Script.Serialization;
using MySql.Data.MySqlClient;
using meridian.bewell;
using meridian.bewell.system;

namespace meridian.bewell.proto
{
	[MetadataType(typeof(territory_categories_meta))]	public partial class territory_categories : admin.db.IDatabaseEntity
	{
		public territory_categories()
		{
			category_territories = new List<territories>();
		}
		private long m_id = 0;
		internal bool mc_id { get; private set; }
		private string m_title = "";
		internal bool mc_title { get; private set; }
		public void LoadFromReader(MySqlDataReader _reader)
		{
			m_id = _reader["id"].GetType() != typeof(System.DBNull) ? _reader.GetInt64("id") : 0;
			mc_id = false;
			m_title = _reader["title"].GetType() != typeof(System.DBNull) ? _reader.GetString("title") : "";
			mc_title = false;
		}
		public void LoadAggregations(Meridian _meridian)
		{
		}
		public void DeleteAggregations()
		{
		}
		public void LoadCompositions(Meridian _meridian)
		{
			string[] keyIds = null;
		}
		public void SaveCompositions(Meridian _meridian)
		{
		}
		public void DeleteCompositions(Meridian _meridian)
		{
			string[] keyIds = null;
		}
		public string ProtoName
		{
			get { return "territory_categories"; }
		}
		/* metafile template 
		internal class territory_categories_meta
		{
			public long id { get; set; }
			public string title { get; set; }
		}
		 metafile template */
		public long id
		{
			get
			{
				return m_id;
			}
			set
			{
				if(m_id != value)
				{
					m_id = value != null ? value : 0;
					mc_id = true;
					// call update worker thread;
				}
			}
		}
		public string title
		{
			get
			{
				return m_title;
			}
			set
			{
				if(m_title != value)
				{
					m_title = value != null ? value : "";
					mc_title = true;
					// call update worker thread;
				}
			}
		}
		private List<territories> category_territories
		{
			get; set; 
		}
		[ScriptIgnore]
		public IEnumerable<territories> Territories
		{
			get { return category_territories; }
		}
		public IEnumerable<territories> GetTerritories()
		{
			return category_territories;
		}
		public territories AddTerritories(territories _item, bool _insertToStore = false)
		{
			if(category_territories.IndexOf(_item) != -1) return _item;
			category_territories.Add(_item);
			_item.category_id = id;
			if(_insertToStore && !Meridian.Default.territoriesStore.Exists(_item.id))
			{
				Meridian.Default.territoriesStore.Insert(_item);
				_item.LoadAggregations(Meridian.Default);
			}
			return _item;
		}
		public territories RemoveTerritories(territories _item, bool _complete = false)
		{
			category_territories.Remove(_item);
			if(_complete) Meridian.Default.territoriesStore.Delete(_item);
			return _item;
		}
	}
}
