SET NAMES utf8;

INSERT INTO `territories` (`id`, `title`) VALUES ('1', 'Россия');
INSERT INTO `territories` (`id`, `title`) VALUES ('2', 'Европа');
INSERT INTO `territories` (`id`, `title`) VALUES ('3', 'Австралия и Океания');
INSERT INTO `territories` (`id`, `title`) VALUES ('4', 'Азия');
INSERT INTO `territories` (`id`, `title`) VALUES ('5', 'Африка');
INSERT INTO `territories` (`id`, `title`) VALUES ('6', 'Северная Америка и Карибы');
INSERT INTO `territories` (`id`, `title`) VALUES ('7', 'Южная Америка');

INSERT INTO `countries` (`id`, `title`, `territory_id`) VALUES ('1', 'Северо-Запад России', '1');
INSERT INTO `countries` (`id`, `title`, `territory_id`) VALUES ('2', 'Средняя полоса России ', '1');
INSERT INTO `countries` (`id`, `title`, `territory_id`) VALUES ('3', 'Кавказские Минеральные Воды', '1');
INSERT INTO `countries` (`id`, `title`, `territory_id`) VALUES ('4', 'Краснодарский край', '1');
INSERT INTO `countries` (`id`, `title`, `territory_id`) VALUES ('5', 'Поволжье', '1');
INSERT INTO `countries` (`id`, `title`, `territory_id`) VALUES ('6', 'Урал', '1');
INSERT INTO `countries` (`id`, `title`, `territory_id`) VALUES ('7', 'Сибирь', '1');
INSERT INTO `countries` (`id`, `title`, `territory_id`) VALUES ('8', 'Дальний Восток', '1');
INSERT INTO `countries` (`id`, `title`, `territory_id`) VALUES ('9', 'Австрия ', '2');
INSERT INTO `countries` (`id`, `title`, `territory_id`) VALUES ('10', 'Черногория ', '2');
INSERT INTO `countries` (`id`, `title`, `territory_id`) VALUES ('11', 'Западная Австралия', '3');
INSERT INTO `countries` (`id`, `title`, `territory_id`) VALUES ('12', 'Северная территория', '3');
INSERT INTO `countries` (`id`, `title`, `territory_id`) VALUES ('13', 'Новый Южный Уэльс', '3');
INSERT INTO `countries` (`id`, `title`, `territory_id`) VALUES ('14', 'Виктория', '3');
INSERT INTO `countries` (`id`, `title`, `territory_id`) VALUES ('15', 'Квинсленд', '3');
INSERT INTO `countries` (`id`, `title`, `territory_id`) VALUES ('16', 'Южная Австралия', '3');
INSERT INTO `countries` (`id`, `title`, `territory_id`) VALUES ('17', 'Тасмания', '3');
INSERT INTO `countries` (`id`, `title`, `territory_id`) VALUES ('18', 'Восточная Азия', '4');
INSERT INTO `countries` (`id`, `title`, `territory_id`) VALUES ('19', 'Западная Азия', '4');
INSERT INTO `countries` (`id`, `title`, `territory_id`) VALUES ('20', 'Юго-Восточная Азия', '4');
INSERT INTO `countries` (`id`, `title`, `territory_id`) VALUES ('21', 'Южная Азия', '4');
INSERT INTO `countries` (`id`, `title`, `territory_id`) VALUES ('22', 'Центральная Азия', '4');
INSERT INTO `countries` (`id`, `title`, `territory_id`) VALUES ('23', 'Алжир', '5');
INSERT INTO `countries` (`id`, `title`, `territory_id`) VALUES ('24', 'Египет', '5');
INSERT INTO `countries` (`id`, `title`, `territory_id`) VALUES ('25', 'Мадагаскар', '5');
INSERT INTO `countries` (`id`, `title`, `territory_id`) VALUES ('26', 'ЮАР', '5');
INSERT INTO `countries` (`id`, `title`, `territory_id`) VALUES ('27', 'Канада', '6');
INSERT INTO `countries` (`id`, `title`, `territory_id`) VALUES ('28', 'США', '6');
INSERT INTO `countries` (`id`, `title`, `territory_id`) VALUES ('29', 'Гаити', '6');
INSERT INTO `countries` (`id`, `title`, `territory_id`) VALUES ('30', 'Гватемала', '6');
INSERT INTO `countries` (`id`, `title`, `territory_id`) VALUES ('31', 'Ямайка', '6');
INSERT INTO `countries` (`id`, `title`, `territory_id`) VALUES ('32', 'Аргентина', '7');
INSERT INTO `countries` (`id`, `title`, `territory_id`) VALUES ('33', 'Бразилия', '7');
INSERT INTO `countries` (`id`, `title`, `territory_id`) VALUES ('34', 'Колумбия', '7');
INSERT INTO `countries` (`id`, `title`, `territory_id`) VALUES ('35', 'Чили', '7');

INSERT INTO `resorts` (`title`, `country_id`) VALUES ('Архангельскя область', '1');
INSERT INTO `resorts` (`title`, `country_id`) VALUES ('Мурманская область', '1');
INSERT INTO `resorts` (`title`, `country_id`) VALUES ('Московская область', '2');
INSERT INTO `resorts` (`title`, `country_id`) VALUES ('Ярославская область', '2');

INSERT INTO `property_categories` (`id`, `title`) VALUES ('1', 'Климатическая зона');
INSERT INTO `property_categories` (`id`, `title`) VALUES ('2', 'Климат');
INSERT INTO `property_categories` (`id`, `title`) VALUES ('3', 'Лечебные факторы');
INSERT INTO `property_categories` (`id`, `title`) VALUES ('4', 'Лечебные процедуры');
INSERT INTO `property_categories` (`id`, `title`) VALUES ('5', 'Дополнительные услуги');
INSERT INTO `property_categories` (`id`, `title`) VALUES ('6', 'Курортное лечение детей');
INSERT INTO `property_categories` (`id`, `title`) VALUES ('7', 'Отдых с детьми (без лечения детей)');
INSERT INTO `property_categories` (`id`, `title`) VALUES ('8', 'Питание');
INSERT INTO `property_categories` (`id`, `title`) VALUES ('9', 'Класс гостиницы');
INSERT INTO `property_categories` (`id`, `title`) VALUES ('10', 'Номер');
INSERT INTO `property_categories` (`id`, `title`) VALUES ('11', 'Адаптированные номера');
INSERT INTO `property_categories` (`id`, `title`) VALUES ('12', 'Конгресс-туризм');
INSERT INTO `property_categories` (`id`, `title`) VALUES ('13', 'Спорт');
INSERT INTO `property_categories` (`id`, `title`) VALUES ('14', 'Досуг');
INSERT INTO `property_categories` (`id`, `title`) VALUES ('15', 'Сервис');
INSERT INTO `property_categories` (`id`, `title`) VALUES ('16', 'Экскурсионные программы');

INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('1', 'Морское побережье', '1');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('2', 'Рядом с водоемом', '1');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('3', 'В лесу', '1');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('4', 'На равнине', '1');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('5', 'В горах', '1');
INSERT INTO `properties` (`id`, `title`, `category_id`, `parent_id`) VALUES ('6', 'до 800 м', '1', '5');
INSERT INTO `properties` (`id`, `title`, `category_id`, `parent_id`) VALUES ('7', 'выше 800 м', '1', '5');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('8', 'Континентальный', '2');
INSERT INTO `properties` (`id`, `title`, `category_id`, `parent_id`) VALUES ('9', 'умеренный', '2', '8');
INSERT INTO `properties` (`id`, `title`, `category_id`, `parent_id`) VALUES ('10', 'средиземноморский', '2', '8');
INSERT INTO `properties` (`id`, `title`, `category_id`, `parent_id`) VALUES ('11', 'тропический', '2', '8');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('12', 'Морской', '2');
INSERT INTO `properties` (`id`, `title`, `category_id`, `parent_id`) VALUES ('13', 'умеренных широт', '2', '12');
INSERT INTO `properties` (`id`, `title`, `category_id`, `parent_id`) VALUES ('14', 'средиземноморский, зоны сухих субтропиков', '2', '12');
INSERT INTO `properties` (`id`, `title`, `category_id`, `parent_id`) VALUES ('15', 'зоны влажных субтропиков', '2', '12');
INSERT INTO `properties` (`id`, `title`, `category_id`, `parent_id`) VALUES ('16', 'тропический', '2', '12');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('17', 'Горный', '2');
INSERT INTO `properties` (`id`, `title`, `category_id`, `parent_id`) VALUES ('18', 'предгорный (до 500м)', '2', '17');
INSERT INTO `properties` (`id`, `title`, `category_id`, `parent_id`) VALUES ('19', 'низкогорный (до 1000 м) ', '2', '17');
INSERT INTO `properties` (`id`, `title`, `category_id`, `parent_id`) VALUES ('20', 'среднегорный (до 2000 м)', '2', '17');
INSERT INTO `properties` (`id`, `title`, `category_id`, `parent_id`) VALUES ('21', 'высокогорный (выше 2000 м)', '2', '17');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('22', 'Степной', '2');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('23', 'Полупустынный', '2');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('24', 'Лечебные грязи', '3');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('25', 'Рапа', '3');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('26', 'Сульфидные воды', '3');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('27', 'Углекислые воды', '3');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('28', 'Радоновые воды', '3');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('29', 'Хлоридные воды', '3');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('30', 'Йодистые воды', '3');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('31', 'Бромистые воды', '3');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('32', 'Кремнистые воды', '3');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('33', 'Мышьяковистые воды', '3');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('34', 'Питьевые воды', '3');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('35', 'Нафталан', '3');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('36', 'Мофетты', '3');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('37', 'Спелеолечебницы (пещеры)', '3');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('38', 'Фумаролы (термальные газы)', '3');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('39', 'Апитерапия', '4');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('40', 'Аюрведа', '4');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('41', 'Гало- или спелеокамера', '4');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('42', 'Гирудотерапия', '4');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('43', 'Грязелечение', '4');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('44', 'Ингаляторий', '4');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('45', 'Мануальная терапия', '4');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('46', 'Массаж', '4');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('47', 'Сухие радоновые ванны', '4');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('48', 'Сухие углекислые ванны', '4');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('49', 'Криотерапия (криосауна)', '4');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('50', 'Психотерапия', '4');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('51', 'Психолог и телесно-ориентированные практики', '4');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('52', 'Талассотерапия', '4');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('53', 'Физиотерапия', '4');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('54', 'Антистресс ', '5');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('55', 'Антиэйджинг', '5');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('56', 'Детокс', '5');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('57', 'Косметический салон', '5');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('58', 'Косметология', '5');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('59', 'Косметическая хирургия', '5');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('60', 'Программы снижения веса', '5');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('61', 'Стоматология (имплантология)', '5');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('62', 'Стоматология (протезирование)', '5');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('63', 'С 0 лет', '6');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('64', 'С 4 лет', '6');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('65', 'С 7 лет', '6');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('66', 'С 0 лет', '7');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('67', 'С 4 лет', '7');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('68', 'С 7 лет', '7');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('69', 'Детская комната', '7');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('70', 'BB (Завтрак)', '8');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('71', 'HB (Полупансион – завтрак и ужин)', '8');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('72', 'FB (Полный пансион)', '8');
INSERT INTO `properties` (`id`, `title`, `category_id`, `parent_id`) VALUES ('73', 'А-ля-карт ', '8', '72');
INSERT INTO `properties` (`id`, `title`, `category_id`, `parent_id`) VALUES ('74', 'Шведский стол', '8', '72');
INSERT INTO `properties` (`id`, `title`, `category_id`, `parent_id`) VALUES ('75', 'Вегетарианское меню', '8', '72');
INSERT INTO `properties` (`id`, `title`, `category_id`, `parent_id`) VALUES ('76', 'Диетическое питание', '8', '72');
INSERT INTO `properties` (`id`, `title`, `category_id`, `parent_id`) VALUES ('77', 'язвенная болезнь', '8', '76');
INSERT INTO `properties` (`id`, `title`, `category_id`, `parent_id`) VALUES ('78', 'гастрит с пониженной кислотностью', '8', '76');
INSERT INTO `properties` (`id`, `title`, `category_id`, `parent_id`) VALUES ('79', 'хронический колит', '8', '76');
INSERT INTO `properties` (`id`, `title`, `category_id`, `parent_id`) VALUES ('80', 'запоры', '8', '76');
INSERT INTO `properties` (`id`, `title`, `category_id`, `parent_id`) VALUES ('81', 'хронические колиты, энтероколиты', '8', '76');
INSERT INTO `properties` (`id`, `title`, `category_id`, `parent_id`) VALUES ('82', 'заболевание печени и желчевыводящих путей', '8', '76');
INSERT INTO `properties` (`id`, `title`, `category_id`, `parent_id`) VALUES ('83', 'целиакия, глютеновая энтеропатия, стеаторея', '8', '76');
INSERT INTO `properties` (`id`, `title`, `category_id`, `parent_id`) VALUES ('84', 'подагра, гиперурикемия', '8', '76');
INSERT INTO `properties` (`id`, `title`, `category_id`, `parent_id`) VALUES ('85', 'заболевание почек', '8', '76');
INSERT INTO `properties` (`id`, `title`, `category_id`, `parent_id`) VALUES ('86', 'ожирение', '8', '76');
INSERT INTO `properties` (`id`, `title`, `category_id`, `parent_id`) VALUES ('87', 'сахарный диабет', '8', '76');
INSERT INTO `properties` (`id`, `title`, `category_id`, `parent_id`) VALUES ('88', 'болезни сердца и сосудов', '8', '76');
INSERT INTO `properties` (`id`, `title`, `category_id`, `parent_id`) VALUES ('89', 'анемия, период после болезней, операций, травм', '8', '76');
INSERT INTO `properties` (`id`, `title`, `category_id`, `parent_id`) VALUES ('90', 'заболевание нервной системы', '8', '76');
INSERT INTO `properties` (`id`, `title`, `category_id`, `parent_id`) VALUES ('91', 'мочекаменная болезнь (фосфатурия)', '8', '76');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('92', '5', '9');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('93', '4', '9');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('94', '3', '9');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('95', '2', '9');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('96', 'Не важно', '9');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('97', 'Кондиционер', '10');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('98', 'Для пациентов на колясках', '11');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('99', 'Для слабовидящих и слепых', '11');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('100', 'Для слабослышащих и глухих', '11');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('101', 'Конференц-зал', '12');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('102', 'Мультимедийное оборудование', '12');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('103', 'Переговорные', '12');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('104', 'Синхронный перевод', '12');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('105', 'Бассейн открытый', '13');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('106', 'Бассейн закрытый', '13');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('107', 'Тренажерный зал', '13');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('108', 'Бильярдная', '13');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('109', 'Футбол', '13');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('110', 'Хоккей', '13');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('111', 'Волейбол', '13');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('112', 'Бадминтон', '13');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('113', 'Теннис', '13');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('114', 'Гольф', '13');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('115', 'Горные лыжи', '13');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('116', 'Серфинг, дайвинг', '13');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('117', 'Спортивный городок', '13');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('118', 'Детская спортивная площадка', '13');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('119', 'Киноконцертный зал', '14');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('120', 'Танцевальная площадка', '14');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('121', 'Парикмахерская ', '15');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('122', 'Прокат спортинвентаря', '15');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('123', 'Обслуживание в номерах', '15');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('124', 'Прачечная', '15');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('125', 'Химчистка', '15');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('126', 'Охраняемая автостоянка', '15');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('127', 'Авиационные кассы', '15');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('128', 'Железнодорожные кассы', '15');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('129', 'Оплата кредитной картой', '15');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('130', 'Банкомат', '15');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('131', 'Сейф в номере', '15');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('132', 'Wi-Fi', '15');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('133', 'Интернет проводной', '15');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('134', 'Почта / телеграф', '15');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('135', 'Отдых с домашними животными', '15');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('136', 'Памятники природы', '16');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('137', 'Исторические памятники', '16');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('138', 'Архитектурные памятники', '16');
INSERT INTO `properties` (`id`, `title`, `category_id`) VALUES ('139', 'Музеи', '16');