/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;
using MySql.Data.MySqlClient;
using meridian.bewell;
using meridian.bewell.system;
using meridian.bewell.proto;
using admin.web.common;

namespace meridian.bewell.controller
{
	public partial class meridian_cure_profiles : BaseUniversalController<cure_profiles>
	{
		public meridian_cure_profiles()
		{
		}
		protected override admin.db.IDataService<cure_profiles> GetService()
		{
			return Meridian.Default.cure_profilesStore;
		}
	}
}
