/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;

namespace meridian.bewell.proto
{
	public partial class citations_meta
	{
		public citations_meta()
		{
		}
		/* metafile template */
		public long id { get; set; }
		public string author { get; set; }
		public string text { get; set; }
		public string picture { get; set; }
		/* metafile template */
	}
}
