/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;

namespace meridian.bewell.proto
{
	public partial class countries_meta
	{
		public countries_meta()
		{
		}
		/* metafile template */
		public long id { get; set; }
		public string title { get; set; }
		public long territory_id { get; set; }
		public string health_factors { get; set; }
		/* metafile template */
	}
}
