/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;

namespace meridian.bewell.proto
{
	public partial class cure_profiles_meta
	{
		public cure_profiles_meta()
		{
		}
		/* metafile template */
		public long id { get; set; }
		public string title { get; set; }
		public long gender_id { get; set; }
		public string css_class { get; set; }
		public int item_order { get; set; }
		/* metafile template */
	}
}
