/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;

namespace meridian.bewell.proto
{
	public partial class deseases_meta
	{
		public deseases_meta()
		{
		}
		/* metafile template */
		public long id { get; set; }
		public string icd_code { get; set; }
		public string title { get; set; }
		public string international_title { get; set; }
		public long profile_id { get; set; }
		/* metafile template */
	}
}
