/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;

namespace meridian.bewell.proto
{
	public partial class entity_fields_meta
	{
		public entity_fields_meta()
		{
		}
		/* metafile template */
		public long id { get; set; }
		public string title { get; set; }
		public string fieldsets { get; set; }
		public int announce_order { get; set; }
		public bool show_in_announce { get; set; }
		public string controller { get; set; }
		public string action { get; set; }
		/* metafile template */
	}
}
