/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;

namespace meridian.bewell.proto
{
	public partial class field_values_meta
	{
		public field_values_meta()
		{
		}
		/* metafile template */
		public long id { get; set; }
		public long entity_id { get; set; }
		public string proto_name { get; set; }
		public long field_id { get; set; }
		public string field_value { get; set; }
		/* metafile template */
	}
}
