/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;

namespace meridian.bewell.proto
{
	public partial class fieldset_fields_order_meta
	{
		public fieldset_fields_order_meta()
		{
		}
		/* metafile template */
		public long id { get; set; }
		public long fieldset_id { get; set; }
		public long field_id { get; set; }
		public int order_number { get; set; }
		/* metafile template */
	}
}
