/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;

namespace meridian.bewell.proto
{
	public partial class fieldsets_meta
	{
		public fieldsets_meta()
		{
		}
		/* metafile template */
		public long id { get; set; }
		public string title { get; set; }
		public string url { get; set; }
		public string proto_name { get; set; }
		public int order_number { get; set; }
		public bool show_gallery { get; set; }
		public bool show_map { get; set; }
		public bool show_in_anounce { get; set; }
		/* metafile template */
	}
}
