/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;

namespace meridian.bewell.proto
{
	public partial class health_factors_meta
	{
		public health_factors_meta()
		{
		}
		/* metafile template */
		public long id { get; set; }
		public string title { get; set; }
		public long parent_id { get; set; }
		public bool show_on_sitemap { get; set; }
		/* metafile template */
	}
}
