/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;

namespace meridian.bewell.proto
{
	public partial class hotels_meta
	{
		public hotels_meta()
		{
		}
		/* metafile template */
		public long id { get; set; }
		public string title { get; set; }
		public int stars { get; set; }
		public long class_id { get; set; }
		public string coordinates { get; set; }
		public bool is_recomended_main_page { get; set; }
		public bool is_recomended { get; set; }
		public string deseases { get; set; }
		public string treatment_options { get; set; }
		public string properties { get; set; }
		public long resort_id { get; set; }
		public bool noyayesgo { get; set; }
		public bool is_published { get; set; }
		/* metafile template */
	}
}
