/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;

namespace meridian.bewell.proto
{
	public partial class hotel_classes_meta
	{
		public hotel_classes_meta()
		{
		}
		/* metafile template */
		public long id { get; set; }
		public string title { get; set; }
		public int stars { get; set; }
		/* metafile template */
	}
}
