/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;

namespace meridian.bewell.proto
{
	public partial class news_meta
	{
		public news_meta()
		{
		}
		/* metafile template */
		public long id { get; set; }
		public long category_id { get; set; }
		public string title { get; set; }
		public string announce { get; set; }
		public string text { get; set; }
		public DateTime publish_date { get; set; }
		public bool is_published { get; set; }
		public string preview { get; set; }
		/* metafile template */
	}
}
