/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;

namespace meridian.bewell.proto
{
	public partial class prices_meta
	{
		public prices_meta()
		{
		}
		/* metafile template */
		public long id { get; set; }
		public long entity_id { get; set; }
		public string proto_name { get; set; }
		public byte month { get; set; }
		public double price { get; set; }
		public string comment { get; set; }
		/* metafile template */
	}
}
