/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;

namespace meridian.bewell.proto
{
	public partial class property_categories_meta
	{
		public property_categories_meta()
		{
		}
		/* metafile template */
		public long id { get; set; }
		public string title { get; set; }
		public bool show_in_search { get; set; }
		public long order_number { get; set; }
		/* metafile template */
	}
}
