/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;

namespace meridian.bewell.proto
{
	public partial class resorts_meta
	{
		public resorts_meta()
		{
		}
		/* metafile template */
		public long id { get; set; }
		public string title { get; set; }
		public long territory_id { get; set; }
		public string cure_profiles { get; set; }
		public string ad_cure_profiles { get; set; }
		public string health_factors { get; set; }
		public bool is_recomended { get; set; }
		public string coordinates { get; set; }
		public bool noyayesgo { get; set; }
		public bool is_published { get; set; }
		/* metafile template */
	}
}
