/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;

namespace meridian.bewell.proto
{
	public partial class seo_metadata_meta
	{
		public seo_metadata_meta()
		{
		}
		/* metafile template */
		public long id { get; set; }
		public long entity_id { get; set; }
		public string proto_name { get; set; }
		public string url { get; set; }
		public string title { get; set; }
		public string keywords { get; set; }
		public string description { get; set; }
		/* metafile template */
	}
}
