/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;

namespace meridian.bewell.proto
{
	public partial class static_pages_meta
	{
		public static_pages_meta()
		{
		}
		/* metafile template */
		public long id { get; set; }
		public string title { get; set; }
		public string html_text { get; set; }
		public string alias { get; set; }
		public string lang { get; set; }
		/* metafile template */
	}
}
