/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;

namespace meridian.bewell.proto
{
	public partial class territories_meta
	{
		public territories_meta()
		{
		}
		/* metafile template */
		public long id { get; set; }
		public string title { get; set; }
		public long parent_id { get; set; }
		public long category_id { get; set; }
		public long nested_category_id { get; set; }
		public long item_order { get; set; }
		public bool in_search { get; set; }
		public string map_key { get; set; }
		/* metafile template */
	}
}
