/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;

namespace meridian.bewell.proto
{
	public partial class accounts_sna_meta
	{
		public accounts_sna_meta()
		{
		}
		/* metafile template */
		public long id { get; set; }
		public string email { get; set; }
		public string facebook_id { get; set; }
		public string vk_id { get; set; }
		public string google_id { get; set; }
		public string odnoklassniki_id { get; set; }
		/* metafile template */
	}
}
