/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;

namespace meridian.bewell.proto
{
	public partial class dictionary_meta
	{
		public dictionary_meta()
		{
		}

        [Editable(false)]
		public long id { get; set; }
        [Display(Name = "Слово")]
        [Required]
		public string word { get; set; }
        [Display(Name = "Значение слова")]
		public string translate { get; set; }
        [DataType("TelerikHtml")]
        [Display(Name = "Описание")]
		public string explanation { get; set; }

        [Display(Name = "Seo метаданные")]
        [DataType("SeoMetadataEdit")]
        public string seo_dummy { get; set; }
        
        [ScaffoldColumn(false)]
        public string EntityName { get; set; }
	}
}
