/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;

namespace meridian.bewell.proto
{
	public partial class entity_photos_meta
	{
		public entity_photos_meta()
		{
		}
		/* metafile template */
		public long id { get; set; }
		public long entity_id { get; set; }
		public int entity_type { get; set; }
		public string guid { get; set; }
		public string original { get; set; }
		public string thumbnail_small { get; set; }
		public string thumbnail_mid { get; set; }
		public string thumbnail_large { get; set; }
		public bool is_main { get; set; }
		public int order_number { get; set; }
		/* metafile template */
	}
}
