/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;

namespace meridian.bewell.proto
{
	public partial class fieldsets_meta
	{
		public fieldsets_meta()
		{
		}
		/* metafile template */
        [Editable(false)]
		public long id { get; set; }

        [Display(Name = "Наименование набора полей")]
		public string title { get; set; }

        [Display(Name = "Состав URL")]
		public string url { get; set; }

        [Display(Name = "Тип сущности")]
		public string proto_name { get; set; }

        [Display(Name = "Порядок сортировки")]
		public int order_number { get; set; }

        [Display(Name = "Отображать галерею")]
		public bool show_gallery { get; set; }

        [Display(Name = "Отображать карту")]
		public bool show_map { get; set; }

        [Display(Name = "Отображать в анонсе")]
		public bool show_in_anounce { get; set; }
		/* metafile template */

        [ScaffoldColumn(false)]
        public string fieldsets_items { get; set; }
	}
}
