/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;
using System.Web.Script.Serialization;

namespace meridian.bewell.proto
{
	public partial class hotel_classes_meta
	{
		public hotel_classes_meta()
		{
		}
		/* metafile template */
        [Editable(false)]
		public long id { get; set; }
        [Display(Name = "Название класса")]
        [Required]
		public string title { get; set; }
        [Display(Name = "Количество звезд")]
        public int stars { get; set; }

        [ScriptIgnore]
        [ScaffoldColumn(false)]
        public string Hotels { get; set; }
		/* metafile template */
	}
}
