/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;

namespace meridian.bewell.proto
{
	public partial class regions_meta
	{
		public regions_meta()
		{
		}
		
        [Editable(false)]
        [Display(Order = 1)]
        public string ProtoName { get; set; }

        [Editable(false)]
        [Display(Order = 2)]
		public long id { get; set; }

        [Display(Name = "Наименование региона", Order = 3)]
		public string title { get; set; }

        [Display(Name = "Территория", Order = 4)]
        [DataType("Lookup")]
		public long territory_id { get; set; }

        [Display(Name = "Факторы, влияющие на здоровье", Order = 5)]
        [DataType("OneToManyEdit")]
        [ScaffoldColumn(false)]
		public string health_factors { get; set; }

        [Display(Name = "Seo метаданные", Order = 6)]
        [DataType("SeoMetadataEdit")]
        public string seo_dummy { get; set; }
	}
}
