/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;

namespace meridian.bewell.proto
{
	public partial class seo_metadata_meta
	{
		public seo_metadata_meta()
		{
		}

        [Editable(false)]
		public long id { get; set; }
        [ScaffoldColumn(false)]
		public int entity_id { get; set; }
        [ScaffoldColumn(false)]
		public string proto_name { get; set; }
        [Display(Name = "Адрес страницы")]
		public string url { get; set; }
        [Display(Name = "Заголовок")]
		public string title { get; set; }
        [Display(Name = "Ключевые слова")]
		public string keywords { get; set; }
        [Display(Name = "Описание")]
		public string description { get; set; }
	}
}
