/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;

namespace meridian.bewell.proto
{
	public partial class territory_categories_meta
	{
		public territory_categories_meta()
		{
		}
		/* metafile template */
        [Editable(false)]
		public long id { get; set; }

        [Display(Name = "Наименование категории территории")]
		public string title { get; set; }
		/* metafile template */

        [ScaffoldColumn(false)]
        public string Territories { get; set; }


	}
}
