/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;
using MySql.Data.MySqlClient;
using meridian.bewell;
using meridian.bewell.system;

namespace meridian.bewell.protoStore
{
	public partial class accounts_snaStore : Meridian.IEntityStore, admin.db.IDataService<proto.accounts_sna>
	{
		public accounts_snaStore()
		{
			m_Items = new SortedList<long, proto.accounts_sna>();
		}
		private SortedList<long, proto.accounts_sna> m_Items;
		public void Commit()
		{
			//throw new NotImplementedException();
		}
		public IQueryable<proto.accounts_sna> GetAll()
		{
			return Queryable.AsQueryable<proto.accounts_sna>(All());
		}
		public proto.accounts_sna GetById(long id)
		{
			return Get(id);
		}
		void admin.db.IDataService<proto.accounts_sna>.Insert(proto.accounts_sna item)
		{
			Insert(item);
		}
		void admin.db.IDataService<proto.accounts_sna>.Delete(proto.accounts_sna item)
		{
			Delete(item);
		}
		public proto.accounts_sna CreateItem()
		{
			return new proto.accounts_sna() {   };
		}
		public void AbortItem(proto.accounts_sna item)
		{
			Delete(item);
		}
		public void Discard()
		{
			;
		}
		void admin.db.IDataService<proto.accounts_sna>.Update(proto.accounts_sna item)
		{
			Persist(item);
		}
		public object GetObject(long _id)
		{
			return Get(_id);
		}
		public System.Type GetObjectType()
		{
			return typeof(proto.accounts_sna);
		}
		public void DeleteById(long _id)
		{
			Delete(Get(_id));
		}
		public void UpdateById(long _id)
		{
			Update(Get(_id));
		}
		public void LoadAggregations(Meridian _meridian)
		{
			foreach(var item in m_Items.Values)
			{
				item.LoadAggregations(_meridian);
			}
		}
		public void Select(MySqlConnection _connection)
		{
			var cmd = new MySqlCommand("SELECT `id`, `email`, `facebook_id`, `vk_id`, `google_id`, `odnoklassniki_id` FROM accounts_sna");
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					var item = new proto.accounts_sna();
					item.LoadFromReader(reader);
					m_Items[item.id] = item;
				}
			}
		}
		public proto.accounts_sna Insert(MySqlConnection _connection, proto.accounts_sna _item)
		{
			var cmd = new MySqlCommand("INSERT INTO accounts_sna ( `email`, `facebook_id`, `vk_id`, `google_id`, `odnoklassniki_id` ) VALUES ( @email, @facebook_id, @vk_id, @google_id, @odnoklassniki_id ); SELECT LAST_INSERT_ID();"); ;
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "email", Value = _item.email });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "facebook_id", Value = _item.facebook_id });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "vk_id", Value = _item.vk_id });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "google_id", Value = _item.google_id });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "odnoklassniki_id", Value = _item.odnoklassniki_id });
			cmd.Connection = _connection;
			_item.id = Convert.ToInt64(cmd.ExecuteScalar());
			m_Items.Add(_item.id, _item);
			_item.LoadAggregations(Meridian.Default);
			return _item;
		}
		public proto.accounts_sna Update(MySqlConnection _connection, proto.accounts_sna _item)
		{
			bool changed =  false;
			var cmdText =  "";
			var cmd = new MySqlCommand("UPDATE accounts_sna SET `email`= @email, `facebook_id`= @facebook_id, `vk_id`= @vk_id, `google_id`= @google_id, `odnoklassniki_id`= @odnoklassniki_id WHERE id=@id"); ;
			if(_item.mc_id)
			{
			}
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "id", Value = _item.id });
			if(_item.mc_email)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`email` = @email";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "email", Value = _item.email != null ? (object)_item.email : DBNull.Value });
			}
			if(_item.mc_facebook_id)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`facebook_id` = @facebook_id";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "facebook_id", Value = _item.facebook_id != null ? (object)_item.facebook_id : DBNull.Value });
			}
			if(_item.mc_vk_id)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`vk_id` = @vk_id";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "vk_id", Value = _item.vk_id != null ? (object)_item.vk_id : DBNull.Value });
			}
			if(_item.mc_google_id)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`google_id` = @google_id";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "google_id", Value = _item.google_id != null ? (object)_item.google_id : DBNull.Value });
			}
			if(_item.mc_odnoklassniki_id)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`odnoklassniki_id` = @odnoklassniki_id";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "odnoklassniki_id", Value = _item.odnoklassniki_id != null ? (object)_item.odnoklassniki_id : DBNull.Value });
			}
			if(changed)
			{
				cmd.CommandText =  "UPDATE accounts_sna SET " + cmdText + " WHERE id=@id";
				cmd.Connection = _connection;
				cmd.ExecuteNonQuery();
				_item.LoadAggregations(Meridian.Default);
			}
			return _item;
		}
		public proto.accounts_sna Delete(MySqlConnection _connection, proto.accounts_sna _item)
		{
			var cmd = new MySqlCommand("DELETE FROM accounts_sna WHERE id=@id"); ;
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "id", Value = _item.id });
			cmd.Connection = _connection;
			cmd.ExecuteScalar();
			return _item;
		}
		public proto.accounts_sna Insert(proto.accounts_sna _item)
		{
			MeridianMonitor.Default.MySqlActionForeground((conn) => Insert(conn, _item));;
			return _item;
		}
		public proto.accounts_sna Persist(proto.accounts_sna _item)
		{
			if(_item.id <= 0)
			{
				_item = Insert(_item);
			}
			_item = Update(_item);
			return _item;
		}
		public proto.accounts_sna Delete(proto.accounts_sna _item)
		{
			_item.DeleteCompositions(Meridian.Default);
			_item.DeleteAggregations();
			m_Items.Remove(_item.id);
			MeridianMonitor.Default.MySqlActionBackground((conn) => Delete(conn, _item));;
			return _item;
		}
		public proto.accounts_sna Update(proto.accounts_sna _item)
		{
			MeridianMonitor.Default.MySqlActionBackground((conn) => Update(conn, _item));;
			return _item;
		}
		public IList<proto.accounts_sna> All()
		{
			return m_Items.Values;
		}
		public proto.accounts_sna Get(long _id)
		{
			return m_Items[_id];
		}
		public bool Exists(long _id)
		{
			return m_Items.ContainsKey(_id);
		}
		public void UpdateSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if (!Exists(_id))
			{
			return;
			}
			var item = Get(_id);
			var cmd = new MySqlCommand("SELECT `id`, `email`, `facebook_id`, `vk_id`, `google_id`, `odnoklassniki_id` FROM accounts_sna WHERE id = " + _id.ToString());
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					item.DeleteCompositions(Meridian.Default);
					item.DeleteAggregations();
					item.LoadFromReader(reader);
					item.LoadAggregations(_meridian);
					item.LoadCompositions(_meridian);
				}
			}
		}
		public void InsertSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if(Exists(_id)) return;;
			var cmd = new MySqlCommand("SELECT `id`, `email`, `facebook_id`, `vk_id`, `google_id`, `odnoklassniki_id` FROM accounts_sna WHERE id = " + _id.ToString());
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					var item = new proto.accounts_sna();
					item.LoadFromReader(reader);
					item.LoadAggregations(_meridian);
					item.LoadCompositions(_meridian);
					m_Items.Add(item.id, item);
				}
			}
		}
		public void DeleteSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if (!Exists(_id))
			{
			return;
			}
			var item = Get(_id);
			item.DeleteCompositions(Meridian.Default);
			item.DeleteAggregations();
			m_Items.Remove(item.id);
		}
	}
}
