/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;
using MySql.Data.MySqlClient;
using meridian.bewell;
using meridian.bewell.system;

namespace meridian.bewell.protoStore
{
	public partial class cure_profilesStore : Meridian.IEntityStore, admin.db.IDataService<proto.cure_profiles>
	{
		public cure_profilesStore()
		{
			m_Items = new SortedList<long, proto.cure_profiles>();
		}
		private SortedList<long, proto.cure_profiles> m_Items;
		public void Commit()
		{
			//throw new NotImplementedException();
		}
		public IQueryable<proto.cure_profiles> GetAll()
		{
			return Queryable.AsQueryable<proto.cure_profiles>(All());
		}
		public proto.cure_profiles GetById(long id)
		{
			return Get(id);
		}
		void admin.db.IDataService<proto.cure_profiles>.Insert(proto.cure_profiles item)
		{
			Insert(item);
		}
		void admin.db.IDataService<proto.cure_profiles>.Delete(proto.cure_profiles item)
		{
			Delete(item);
		}
		public proto.cure_profiles CreateItem()
		{
			return new proto.cure_profiles() {   };
		}
		public void AbortItem(proto.cure_profiles item)
		{
			Delete(item);
		}
		public void Discard()
		{
			;
		}
		void admin.db.IDataService<proto.cure_profiles>.Update(proto.cure_profiles item)
		{
			Persist(item);
		}
		public object GetObject(long _id)
		{
			return Get(_id);
		}
		public System.Type GetObjectType()
		{
			return typeof(proto.cure_profiles);
		}
		public void DeleteById(long _id)
		{
			Delete(Get(_id));
		}
		public void UpdateById(long _id)
		{
			Update(Get(_id));
		}
		public void LoadAggregations(Meridian _meridian)
		{
			foreach(var item in m_Items.Values)
			{
				item.LoadAggregations(_meridian);
			}
		}
		public void LoadCompositions(Meridian _meridian)
		{
			foreach(var item in m_Items.Values)
			{
				item.LoadCompositions(_meridian);
			}
		}
		public void Select(MySqlConnection _connection)
		{
			var cmd = new MySqlCommand("SELECT `id`, `title`, `gender_id`, `css_class`, `item_order` FROM cure_profiles");
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					var item = new proto.cure_profiles();
					item.LoadFromReader(reader);
					m_Items[item.id] = item;
				}
			}
		}
		public proto.cure_profiles Insert(MySqlConnection _connection, proto.cure_profiles _item)
		{
			var cmd = new MySqlCommand("INSERT INTO cure_profiles ( `title`, `gender_id`, `css_class`, `item_order` ) VALUES ( @title, @gender_id, @css_class, @item_order ); SELECT LAST_INSERT_ID();"); ;
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "title", Value = _item.title });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "gender_id", Value = _item.gender_id });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "css_class", Value = _item.css_class });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "item_order", Value = _item.item_order });
			cmd.Connection = _connection;
			_item.id = Convert.ToInt64(cmd.ExecuteScalar());
			m_Items.Add(_item.id, _item);
			_item.LoadAggregations(Meridian.Default);
			return _item;
		}
		public proto.cure_profiles Update(MySqlConnection _connection, proto.cure_profiles _item)
		{
			bool changed =  false;
			var cmdText =  "";
			var cmd = new MySqlCommand("UPDATE cure_profiles SET `title`= @title, `gender_id`= @gender_id, `css_class`= @css_class, `item_order`= @item_order WHERE id=@id"); ;
			if(_item.mc_id)
			{
			}
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "id", Value = _item.id });
			if(_item.mc_title)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`title` = @title";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "title", Value = _item.title != null ? (object)_item.title : DBNull.Value });
			}
			if(_item.mc_gender_id)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`gender_id` = @gender_id";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "gender_id", Value = _item.gender_id });
			}
			if(_item.mc_css_class)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`css_class` = @css_class";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "css_class", Value = _item.css_class != null ? (object)_item.css_class : DBNull.Value });
			}
			if(_item.mc_item_order)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`item_order` = @item_order";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "item_order", Value = _item.item_order });
			}
			if(changed)
			{
				cmd.CommandText =  "UPDATE cure_profiles SET " + cmdText + " WHERE id=@id";
				cmd.Connection = _connection;
				cmd.ExecuteNonQuery();
				_item.LoadAggregations(Meridian.Default);
			}
			return _item;
		}
		public proto.cure_profiles Delete(MySqlConnection _connection, proto.cure_profiles _item)
		{
			var cmd = new MySqlCommand("DELETE FROM cure_profiles WHERE id=@id"); ;
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "id", Value = _item.id });
			cmd.Connection = _connection;
			cmd.ExecuteScalar();
			return _item;
		}
		public proto.cure_profiles Insert(proto.cure_profiles _item)
		{
			MeridianMonitor.Default.MySqlActionForeground((conn) => Insert(conn, _item));;
			return _item;
		}
		public proto.cure_profiles Persist(proto.cure_profiles _item)
		{
			if(_item.id <= 0)
			{
				_item = Insert(_item);
			}
			_item = Update(_item);
			return _item;
		}
		public proto.cure_profiles Delete(proto.cure_profiles _item)
		{
			_item.DeleteCompositions(Meridian.Default);
			_item.DeleteAggregations();
			m_Items.Remove(_item.id);
			MeridianMonitor.Default.MySqlActionBackground((conn) => Delete(conn, _item));;
			return _item;
		}
		public proto.cure_profiles Update(proto.cure_profiles _item)
		{
			MeridianMonitor.Default.MySqlActionBackground((conn) => Update(conn, _item));;
			return _item;
		}
		public IList<proto.cure_profiles> All()
		{
			return m_Items.Values;
		}
		public proto.cure_profiles Get(long _id)
		{
			return m_Items[_id];
		}
		public bool Exists(long _id)
		{
			return m_Items.ContainsKey(_id);
		}
		public void UpdateSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if (!Exists(_id))
			{
			return;
			}
			var item = Get(_id);
			var cmd = new MySqlCommand("SELECT `id`, `title`, `gender_id`, `css_class`, `item_order` FROM cure_profiles WHERE id = " + _id.ToString());
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					item.DeleteCompositions(Meridian.Default);
					item.DeleteAggregations();
					item.LoadFromReader(reader);
					item.LoadAggregations(_meridian);
					item.LoadCompositions(_meridian);
				}
			}
		}
		public void InsertSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if(Exists(_id)) return;;
			var cmd = new MySqlCommand("SELECT `id`, `title`, `gender_id`, `css_class`, `item_order` FROM cure_profiles WHERE id = " + _id.ToString());
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					var item = new proto.cure_profiles();
					item.LoadFromReader(reader);
					item.LoadAggregations(_meridian);
					item.LoadCompositions(_meridian);
					m_Items.Add(item.id, item);
				}
			}
		}
		public void DeleteSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if (!Exists(_id))
			{
			return;
			}
			var item = Get(_id);
			item.DeleteCompositions(Meridian.Default);
			item.DeleteAggregations();
			m_Items.Remove(item.id);
		}
	}
}
