/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;
using MySql.Data.MySqlClient;
using meridian.bewell;
using meridian.bewell.system;

namespace meridian.bewell.protoStore
{
	public partial class deseasesStore : Meridian.IEntityStore, admin.db.IDataService<proto.deseases>
	{
		public deseasesStore()
		{
			m_Items = new SortedList<long, proto.deseases>();
		}
		private SortedList<long, proto.deseases> m_Items;
		public void Commit()
		{
			//throw new NotImplementedException();
		}
		public IQueryable<proto.deseases> GetAll()
		{
			return Queryable.AsQueryable<proto.deseases>(All());
		}
		public proto.deseases GetById(long id)
		{
			return Get(id);
		}
		void admin.db.IDataService<proto.deseases>.Insert(proto.deseases item)
		{
			Insert(item);
		}
		void admin.db.IDataService<proto.deseases>.Delete(proto.deseases item)
		{
			Delete(item);
		}
		public proto.deseases CreateItem()
		{
			return new proto.deseases() {   };
		}
		public void AbortItem(proto.deseases item)
		{
			Delete(item);
		}
		public void Discard()
		{
			;
		}
		void admin.db.IDataService<proto.deseases>.Update(proto.deseases item)
		{
			Persist(item);
		}
		public object GetObject(long _id)
		{
			return Get(_id);
		}
		public System.Type GetObjectType()
		{
			return typeof(proto.deseases);
		}
		public void DeleteById(long _id)
		{
			Delete(Get(_id));
		}
		public void UpdateById(long _id)
		{
			Update(Get(_id));
		}
		public void LoadAggregations(Meridian _meridian)
		{
			foreach(var item in m_Items.Values)
			{
				item.LoadAggregations(_meridian);
			}
		}
		public void LoadCompositions(Meridian _meridian)
		{
			foreach(var item in m_Items.Values)
			{
				item.LoadCompositions(_meridian);
			}
		}
		public void Select(MySqlConnection _connection)
		{
			var cmd = new MySqlCommand("SELECT `id`, `icd_code`, `title`, `international_title`, `profile_id` FROM deseases");
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					var item = new proto.deseases();
					item.LoadFromReader(reader);
					m_Items[item.id] = item;
				}
			}
		}
		public proto.deseases Insert(MySqlConnection _connection, proto.deseases _item)
		{
			var cmd = new MySqlCommand("INSERT INTO deseases ( `icd_code`, `title`, `international_title`, `profile_id` ) VALUES ( @icd_code, @title, @international_title, @profile_id ); SELECT LAST_INSERT_ID();"); ;
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "icd_code", Value = _item.icd_code });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "title", Value = _item.title });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "international_title", Value = _item.international_title });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "profile_id", Value = _item.profile_id });
			cmd.Connection = _connection;
			_item.id = Convert.ToInt64(cmd.ExecuteScalar());
			m_Items.Add(_item.id, _item);
			_item.LoadAggregations(Meridian.Default);
			return _item;
		}
		public proto.deseases Update(MySqlConnection _connection, proto.deseases _item)
		{
			bool changed =  false;
			var cmdText =  "";
			var cmd = new MySqlCommand("UPDATE deseases SET `icd_code`= @icd_code, `title`= @title, `international_title`= @international_title, `profile_id`= @profile_id WHERE id=@id"); ;
			if(_item.mc_id)
			{
			}
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "id", Value = _item.id });
			if(_item.mc_icd_code)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`icd_code` = @icd_code";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "icd_code", Value = _item.icd_code != null ? (object)_item.icd_code : DBNull.Value });
			}
			if(_item.mc_title)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`title` = @title";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "title", Value = _item.title != null ? (object)_item.title : DBNull.Value });
			}
			if(_item.mc_international_title)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`international_title` = @international_title";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "international_title", Value = _item.international_title != null ? (object)_item.international_title : DBNull.Value });
			}
			if(_item.mc_profile_id)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`profile_id` = @profile_id";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "profile_id", Value = _item.profile_id });
			}
			if(changed)
			{
				cmd.CommandText =  "UPDATE deseases SET " + cmdText + " WHERE id=@id";
				cmd.Connection = _connection;
				cmd.ExecuteNonQuery();
				_item.LoadAggregations(Meridian.Default);
			}
			return _item;
		}
		public proto.deseases Delete(MySqlConnection _connection, proto.deseases _item)
		{
			var cmd = new MySqlCommand("DELETE FROM deseases WHERE id=@id"); ;
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "id", Value = _item.id });
			cmd.Connection = _connection;
			cmd.ExecuteScalar();
			return _item;
		}
		public proto.deseases Insert(proto.deseases _item)
		{
			MeridianMonitor.Default.MySqlActionForeground((conn) => Insert(conn, _item));;
			return _item;
		}
		public proto.deseases Persist(proto.deseases _item)
		{
			if(_item.id <= 0)
			{
				_item = Insert(_item);
			}
			_item = Update(_item);
			return _item;
		}
		public proto.deseases Delete(proto.deseases _item)
		{
			_item.DeleteCompositions(Meridian.Default);
			_item.DeleteAggregations();
			m_Items.Remove(_item.id);
			MeridianMonitor.Default.MySqlActionBackground((conn) => Delete(conn, _item));;
			return _item;
		}
		public proto.deseases Update(proto.deseases _item)
		{
			MeridianMonitor.Default.MySqlActionBackground((conn) => Update(conn, _item));;
			return _item;
		}
		public IList<proto.deseases> All()
		{
			return m_Items.Values;
		}
		public proto.deseases Get(long _id)
		{
			return m_Items[_id];
		}
		public bool Exists(long _id)
		{
			return m_Items.ContainsKey(_id);
		}
		public void UpdateSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if (!Exists(_id))
			{
			return;
			}
			var item = Get(_id);
			var cmd = new MySqlCommand("SELECT `id`, `icd_code`, `title`, `international_title`, `profile_id` FROM deseases WHERE id = " + _id.ToString());
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					item.DeleteCompositions(Meridian.Default);
					item.DeleteAggregations();
					item.LoadFromReader(reader);
					item.LoadAggregations(_meridian);
					item.LoadCompositions(_meridian);
				}
			}
		}
		public void InsertSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if(Exists(_id)) return;;
			var cmd = new MySqlCommand("SELECT `id`, `icd_code`, `title`, `international_title`, `profile_id` FROM deseases WHERE id = " + _id.ToString());
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					var item = new proto.deseases();
					item.LoadFromReader(reader);
					item.LoadAggregations(_meridian);
					item.LoadCompositions(_meridian);
					m_Items.Add(item.id, item);
				}
			}
		}
		public void DeleteSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if (!Exists(_id))
			{
			return;
			}
			var item = Get(_id);
			item.DeleteCompositions(Meridian.Default);
			item.DeleteAggregations();
			m_Items.Remove(item.id);
		}
	}
}
