/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;
using MySql.Data.MySqlClient;
using meridian.bewell;
using meridian.bewell.system;

namespace meridian.bewell.protoStore
{
	public partial class dictionaryStore : Meridian.IEntityStore, admin.db.IDataService<proto.dictionary>
	{
		public dictionaryStore()
		{
			m_Items = new SortedList<long, proto.dictionary>();
		}
		private SortedList<long, proto.dictionary> m_Items;
		public void Commit()
		{
			//throw new NotImplementedException();
		}
		public IQueryable<proto.dictionary> GetAll()
		{
			return Queryable.AsQueryable<proto.dictionary>(All());
		}
		public proto.dictionary GetById(long id)
		{
			return Get(id);
		}
		void admin.db.IDataService<proto.dictionary>.Insert(proto.dictionary item)
		{
			Insert(item);
		}
		void admin.db.IDataService<proto.dictionary>.Delete(proto.dictionary item)
		{
			Delete(item);
		}
		public proto.dictionary CreateItem()
		{
			return new proto.dictionary() {   };
		}
		public void AbortItem(proto.dictionary item)
		{
			Delete(item);
		}
		public void Discard()
		{
			;
		}
		void admin.db.IDataService<proto.dictionary>.Update(proto.dictionary item)
		{
			Persist(item);
		}
		public object GetObject(long _id)
		{
			return Get(_id);
		}
		public System.Type GetObjectType()
		{
			return typeof(proto.dictionary);
		}
		public void DeleteById(long _id)
		{
			Delete(Get(_id));
		}
		public void UpdateById(long _id)
		{
			Update(Get(_id));
		}
		public void LoadAggregations(Meridian _meridian)
		{
			foreach(var item in m_Items.Values)
			{
				item.LoadAggregations(_meridian);
			}
		}
		public void Select(MySqlConnection _connection)
		{
			var cmd = new MySqlCommand("SELECT `id`, `word`, `translate`, `explanation` FROM dictionary");
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					var item = new proto.dictionary();
					item.LoadFromReader(reader);
					m_Items[item.id] = item;
				}
			}
		}
		public proto.dictionary Insert(MySqlConnection _connection, proto.dictionary _item)
		{
			var cmd = new MySqlCommand("INSERT INTO dictionary ( `word`, `translate`, `explanation` ) VALUES ( @word, @translate, @explanation ); SELECT LAST_INSERT_ID();"); ;
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "word", Value = _item.word });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "translate", Value = _item.translate });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "explanation", Value = _item.explanation });
			cmd.Connection = _connection;
			_item.id = Convert.ToInt64(cmd.ExecuteScalar());
			m_Items.Add(_item.id, _item);
			_item.LoadAggregations(Meridian.Default);
			return _item;
		}
		public proto.dictionary Update(MySqlConnection _connection, proto.dictionary _item)
		{
			bool changed =  false;
			var cmdText =  "";
			var cmd = new MySqlCommand("UPDATE dictionary SET `word`= @word, `translate`= @translate, `explanation`= @explanation WHERE id=@id"); ;
			if(_item.mc_id)
			{
			}
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "id", Value = _item.id });
			if(_item.mc_word)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`word` = @word";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "word", Value = _item.word != null ? (object)_item.word : DBNull.Value });
			}
			if(_item.mc_translate)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`translate` = @translate";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "translate", Value = _item.translate != null ? (object)_item.translate : DBNull.Value });
			}
			if(_item.mc_explanation)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`explanation` = @explanation";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "explanation", Value = _item.explanation != null ? (object)_item.explanation : DBNull.Value });
			}
			if(changed)
			{
				cmd.CommandText =  "UPDATE dictionary SET " + cmdText + " WHERE id=@id";
				cmd.Connection = _connection;
				cmd.ExecuteNonQuery();
				_item.LoadAggregations(Meridian.Default);
			}
			return _item;
		}
		public proto.dictionary Delete(MySqlConnection _connection, proto.dictionary _item)
		{
			var cmd = new MySqlCommand("DELETE FROM dictionary WHERE id=@id"); ;
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "id", Value = _item.id });
			cmd.Connection = _connection;
			cmd.ExecuteScalar();
			return _item;
		}
		public proto.dictionary Insert(proto.dictionary _item)
		{
			MeridianMonitor.Default.MySqlActionForeground((conn) => Insert(conn, _item));;
			return _item;
		}
		public proto.dictionary Persist(proto.dictionary _item)
		{
			if(_item.id <= 0)
			{
				_item = Insert(_item);
			}
			_item = Update(_item);
			return _item;
		}
		public proto.dictionary Delete(proto.dictionary _item)
		{
			_item.DeleteCompositions(Meridian.Default);
			_item.DeleteAggregations();
			m_Items.Remove(_item.id);
			MeridianMonitor.Default.MySqlActionBackground((conn) => Delete(conn, _item));;
			return _item;
		}
		public proto.dictionary Update(proto.dictionary _item)
		{
			MeridianMonitor.Default.MySqlActionBackground((conn) => Update(conn, _item));;
			return _item;
		}
		public IList<proto.dictionary> All()
		{
			return m_Items.Values;
		}
		public proto.dictionary Get(long _id)
		{
			return m_Items[_id];
		}
		public bool Exists(long _id)
		{
			return m_Items.ContainsKey(_id);
		}
		public void UpdateSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if (!Exists(_id))
			{
			return;
			}
			var item = Get(_id);
			var cmd = new MySqlCommand("SELECT `id`, `word`, `translate`, `explanation` FROM dictionary WHERE id = " + _id.ToString());
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					item.DeleteCompositions(Meridian.Default);
					item.DeleteAggregations();
					item.LoadFromReader(reader);
					item.LoadAggregations(_meridian);
					item.LoadCompositions(_meridian);
				}
			}
		}
		public void InsertSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if(Exists(_id)) return;;
			var cmd = new MySqlCommand("SELECT `id`, `word`, `translate`, `explanation` FROM dictionary WHERE id = " + _id.ToString());
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					var item = new proto.dictionary();
					item.LoadFromReader(reader);
					item.LoadAggregations(_meridian);
					item.LoadCompositions(_meridian);
					m_Items.Add(item.id, item);
				}
			}
		}
		public void DeleteSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if (!Exists(_id))
			{
			return;
			}
			var item = Get(_id);
			item.DeleteCompositions(Meridian.Default);
			item.DeleteAggregations();
			m_Items.Remove(item.id);
		}
	}
}
