/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;
using MySql.Data.MySqlClient;
using meridian.bewell;
using meridian.bewell.system;

namespace meridian.bewell.protoStore
{
	public partial class entity_fieldsStore : Meridian.IEntityStore, admin.db.IDataService<proto.entity_fields>
	{
		public entity_fieldsStore()
		{
			m_Items = new SortedList<long, proto.entity_fields>();
		}
		private SortedList<long, proto.entity_fields> m_Items;
		public void Commit()
		{
			//throw new NotImplementedException();
		}
		public IQueryable<proto.entity_fields> GetAll()
		{
			return Queryable.AsQueryable<proto.entity_fields>(All());
		}
		public proto.entity_fields GetById(long id)
		{
			return Get(id);
		}
		void admin.db.IDataService<proto.entity_fields>.Insert(proto.entity_fields item)
		{
			Insert(item);
		}
		void admin.db.IDataService<proto.entity_fields>.Delete(proto.entity_fields item)
		{
			Delete(item);
		}
		public proto.entity_fields CreateItem()
		{
			return new proto.entity_fields() {   };
		}
		public void AbortItem(proto.entity_fields item)
		{
			Delete(item);
		}
		public void Discard()
		{
			;
		}
		void admin.db.IDataService<proto.entity_fields>.Update(proto.entity_fields item)
		{
			Persist(item);
		}
		public object GetObject(long _id)
		{
			return Get(_id);
		}
		public System.Type GetObjectType()
		{
			return typeof(proto.entity_fields);
		}
		public void DeleteById(long _id)
		{
			Delete(Get(_id));
		}
		public void UpdateById(long _id)
		{
			Update(Get(_id));
		}
		public void LoadAggregations(Meridian _meridian)
		{
			foreach(var item in m_Items.Values)
			{
				item.LoadAggregations(_meridian);
			}
		}
		public void LoadCompositions(Meridian _meridian)
		{
			foreach(var item in m_Items.Values)
			{
				item.LoadCompositions(_meridian);
			}
		}
		public void Select(MySqlConnection _connection)
		{
			var cmd = new MySqlCommand("SELECT `id`, `title`, `fieldsets`, `announce_order`, `show_in_announce`, `controller`, `action` FROM entity_fields");
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					var item = new proto.entity_fields();
					item.LoadFromReader(reader);
					m_Items[item.id] = item;
				}
			}
		}
		public proto.entity_fields Insert(MySqlConnection _connection, proto.entity_fields _item)
		{
			var cmd = new MySqlCommand("INSERT INTO entity_fields ( `title`, `fieldsets`, `announce_order`, `show_in_announce`, `controller`, `action` ) VALUES ( @title, @fieldsets, @announce_order, @show_in_announce, @controller, @action ); SELECT LAST_INSERT_ID();"); ;
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "title", Value = _item.title });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "fieldsets", Value = _item.fieldsets });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "announce_order", Value = _item.announce_order });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "show_in_announce", Value = _item.show_in_announce });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "controller", Value = _item.controller });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "action", Value = _item.action });
			cmd.Connection = _connection;
			_item.id = Convert.ToInt64(cmd.ExecuteScalar());
			m_Items.Add(_item.id, _item);
			_item.LoadAggregations(Meridian.Default);
			return _item;
		}
		public proto.entity_fields Update(MySqlConnection _connection, proto.entity_fields _item)
		{
			bool changed =  false;
			var cmdText =  "";
			var cmd = new MySqlCommand("UPDATE entity_fields SET `title`= @title, `fieldsets`= @fieldsets, `announce_order`= @announce_order, `show_in_announce`= @show_in_announce, `controller`= @controller, `action`= @action WHERE id=@id"); ;
			if(_item.mc_id)
			{
			}
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "id", Value = _item.id });
			if(_item.mc_title)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`title` = @title";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "title", Value = _item.title != null ? (object)_item.title : DBNull.Value });
			}
			if(_item.mc_fieldsets)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`fieldsets` = @fieldsets";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "fieldsets", Value = _item.fieldsets != null ? (object)_item.fieldsets : DBNull.Value });
			}
			if(_item.mc_announce_order)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`announce_order` = @announce_order";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "announce_order", Value = _item.announce_order });
			}
			if(_item.mc_show_in_announce)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`show_in_announce` = @show_in_announce";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "show_in_announce", Value = _item.show_in_announce });
			}
			if(_item.mc_controller)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`controller` = @controller";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "controller", Value = _item.controller != null ? (object)_item.controller : DBNull.Value });
			}
			if(_item.mc_action)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`action` = @action";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "action", Value = _item.action != null ? (object)_item.action : DBNull.Value });
			}
			if(changed)
			{
				cmd.CommandText =  "UPDATE entity_fields SET " + cmdText + " WHERE id=@id";
				cmd.Connection = _connection;
				cmd.ExecuteNonQuery();
				_item.LoadAggregations(Meridian.Default);
			}
			return _item;
		}
		public proto.entity_fields Delete(MySqlConnection _connection, proto.entity_fields _item)
		{
			var cmd = new MySqlCommand("DELETE FROM entity_fields WHERE id=@id"); ;
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "id", Value = _item.id });
			cmd.Connection = _connection;
			cmd.ExecuteScalar();
			return _item;
		}
		public proto.entity_fields Insert(proto.entity_fields _item)
		{
			MeridianMonitor.Default.MySqlActionForeground((conn) => Insert(conn, _item));;
			return _item;
		}
		public proto.entity_fields Persist(proto.entity_fields _item)
		{
			if(_item.id <= 0)
			{
				_item = Insert(_item);
			}
			_item = Update(_item);
			return _item;
		}
		public proto.entity_fields Delete(proto.entity_fields _item)
		{
			_item.DeleteCompositions(Meridian.Default);
			_item.DeleteAggregations();
			m_Items.Remove(_item.id);
			MeridianMonitor.Default.MySqlActionBackground((conn) => Delete(conn, _item));;
			return _item;
		}
		public proto.entity_fields Update(proto.entity_fields _item)
		{
			MeridianMonitor.Default.MySqlActionBackground((conn) => Update(conn, _item));;
			return _item;
		}
		public IList<proto.entity_fields> All()
		{
			return m_Items.Values;
		}
		public proto.entity_fields Get(long _id)
		{
			return m_Items[_id];
		}
		public bool Exists(long _id)
		{
			return m_Items.ContainsKey(_id);
		}
		public void UpdateSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if (!Exists(_id))
			{
			return;
			}
			var item = Get(_id);
			var cmd = new MySqlCommand("SELECT `id`, `title`, `fieldsets`, `announce_order`, `show_in_announce`, `controller`, `action` FROM entity_fields WHERE id = " + _id.ToString());
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					item.DeleteCompositions(Meridian.Default);
					item.DeleteAggregations();
					item.LoadFromReader(reader);
					item.LoadAggregations(_meridian);
					item.LoadCompositions(_meridian);
				}
			}
		}
		public void InsertSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if(Exists(_id)) return;;
			var cmd = new MySqlCommand("SELECT `id`, `title`, `fieldsets`, `announce_order`, `show_in_announce`, `controller`, `action` FROM entity_fields WHERE id = " + _id.ToString());
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					var item = new proto.entity_fields();
					item.LoadFromReader(reader);
					item.LoadAggregations(_meridian);
					item.LoadCompositions(_meridian);
					m_Items.Add(item.id, item);
				}
			}
		}
		public void DeleteSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if (!Exists(_id))
			{
			return;
			}
			var item = Get(_id);
			item.DeleteCompositions(Meridian.Default);
			item.DeleteAggregations();
			m_Items.Remove(item.id);
		}
	}
}
