/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;
using MySql.Data.MySqlClient;
using meridian.bewell;
using meridian.bewell.system;

namespace meridian.bewell.protoStore
{
	public partial class entity_photosStore : Meridian.IEntityStore, admin.db.IDataService<proto.entity_photos>
	{
		public entity_photosStore()
		{
			m_Items = new SortedList<long, proto.entity_photos>();
		}
		private SortedList<long, proto.entity_photos> m_Items;
		public void Commit()
		{
			//throw new NotImplementedException();
		}
		public IQueryable<proto.entity_photos> GetAll()
		{
			return Queryable.AsQueryable<proto.entity_photos>(All());
		}
		public proto.entity_photos GetById(long id)
		{
			return Get(id);
		}
		void admin.db.IDataService<proto.entity_photos>.Insert(proto.entity_photos item)
		{
			Insert(item);
		}
		void admin.db.IDataService<proto.entity_photos>.Delete(proto.entity_photos item)
		{
			Delete(item);
		}
		public proto.entity_photos CreateItem()
		{
			return new proto.entity_photos() {   };
		}
		public void AbortItem(proto.entity_photos item)
		{
			Delete(item);
		}
		public void Discard()
		{
			;
		}
		void admin.db.IDataService<proto.entity_photos>.Update(proto.entity_photos item)
		{
			Persist(item);
		}
		public object GetObject(long _id)
		{
			return Get(_id);
		}
		public System.Type GetObjectType()
		{
			return typeof(proto.entity_photos);
		}
		public void DeleteById(long _id)
		{
			Delete(Get(_id));
		}
		public void UpdateById(long _id)
		{
			Update(Get(_id));
		}
		public void LoadAggregations(Meridian _meridian)
		{
			foreach(var item in m_Items.Values)
			{
				item.LoadAggregations(_meridian);
			}
		}
		public void Select(MySqlConnection _connection)
		{
			var cmd = new MySqlCommand("SELECT `id`, `entity_id`, `proto_name`, `guid`, `original`, `thumbnail_small`, `thumbnail_mid`, `thumbnail_large`, `is_main`, `order_number` FROM entity_photos");
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					var item = new proto.entity_photos();
					item.LoadFromReader(reader);
					m_Items[item.id] = item;
				}
			}
		}
		public proto.entity_photos Insert(MySqlConnection _connection, proto.entity_photos _item)
		{
			var cmd = new MySqlCommand("INSERT INTO entity_photos ( `entity_id`, `proto_name`, `guid`, `original`, `thumbnail_small`, `thumbnail_mid`, `thumbnail_large`, `is_main`, `order_number` ) VALUES ( @entity_id, @proto_name, @guid, @original, @thumbnail_small, @thumbnail_mid, @thumbnail_large, @is_main, @order_number ); SELECT LAST_INSERT_ID();"); ;
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "entity_id", Value = _item.entity_id });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "proto_name", Value = _item.proto_name });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "guid", Value = _item.guid });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "original", Value = _item.original });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "thumbnail_small", Value = _item.thumbnail_small });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "thumbnail_mid", Value = _item.thumbnail_mid });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "thumbnail_large", Value = _item.thumbnail_large });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "is_main", Value = _item.is_main });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "order_number", Value = _item.order_number });
			cmd.Connection = _connection;
			_item.id = Convert.ToInt64(cmd.ExecuteScalar());
			m_Items.Add(_item.id, _item);
			_item.LoadAggregations(Meridian.Default);
			return _item;
		}
		public proto.entity_photos Update(MySqlConnection _connection, proto.entity_photos _item)
		{
			bool changed =  false;
			var cmdText =  "";
			var cmd = new MySqlCommand("UPDATE entity_photos SET `entity_id`= @entity_id, `proto_name`= @proto_name, `guid`= @guid, `original`= @original, `thumbnail_small`= @thumbnail_small, `thumbnail_mid`= @thumbnail_mid, `thumbnail_large`= @thumbnail_large, `is_main`= @is_main, `order_number`= @order_number WHERE id=@id"); ;
			if(_item.mc_id)
			{
			}
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "id", Value = _item.id });
			if(_item.mc_entity_id)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`entity_id` = @entity_id";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "entity_id", Value = _item.entity_id });
			}
			if(_item.mc_proto_name)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`proto_name` = @proto_name";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "proto_name", Value = _item.proto_name != null ? (object)_item.proto_name : DBNull.Value });
			}
			if(_item.mc_guid)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`guid` = @guid";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "guid", Value = _item.guid != null ? (object)_item.guid : DBNull.Value });
			}
			if(_item.mc_original)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`original` = @original";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "original", Value = _item.original != null ? (object)_item.original : DBNull.Value });
			}
			if(_item.mc_thumbnail_small)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`thumbnail_small` = @thumbnail_small";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "thumbnail_small", Value = _item.thumbnail_small != null ? (object)_item.thumbnail_small : DBNull.Value });
			}
			if(_item.mc_thumbnail_mid)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`thumbnail_mid` = @thumbnail_mid";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "thumbnail_mid", Value = _item.thumbnail_mid != null ? (object)_item.thumbnail_mid : DBNull.Value });
			}
			if(_item.mc_thumbnail_large)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`thumbnail_large` = @thumbnail_large";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "thumbnail_large", Value = _item.thumbnail_large != null ? (object)_item.thumbnail_large : DBNull.Value });
			}
			if(_item.mc_is_main)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`is_main` = @is_main";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "is_main", Value = _item.is_main });
			}
			if(_item.mc_order_number)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`order_number` = @order_number";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "order_number", Value = _item.order_number });
			}
			if(changed)
			{
				cmd.CommandText =  "UPDATE entity_photos SET " + cmdText + " WHERE id=@id";
				cmd.Connection = _connection;
				cmd.ExecuteNonQuery();
				_item.LoadAggregations(Meridian.Default);
			}
			return _item;
		}
		public proto.entity_photos Delete(MySqlConnection _connection, proto.entity_photos _item)
		{
			var cmd = new MySqlCommand("DELETE FROM entity_photos WHERE id=@id"); ;
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "id", Value = _item.id });
			cmd.Connection = _connection;
			cmd.ExecuteScalar();
			return _item;
		}
		public proto.entity_photos Insert(proto.entity_photos _item)
		{
			MeridianMonitor.Default.MySqlActionForeground((conn) => Insert(conn, _item));;
			return _item;
		}
		public proto.entity_photos Persist(proto.entity_photos _item)
		{
			if(_item.id <= 0)
			{
				_item = Insert(_item);
			}
			_item = Update(_item);
			return _item;
		}
		public proto.entity_photos Delete(proto.entity_photos _item)
		{
			_item.DeleteCompositions(Meridian.Default);
			_item.DeleteAggregations();
			m_Items.Remove(_item.id);
			MeridianMonitor.Default.MySqlActionBackground((conn) => Delete(conn, _item));;
			return _item;
		}
		public proto.entity_photos Update(proto.entity_photos _item)
		{
			MeridianMonitor.Default.MySqlActionBackground((conn) => Update(conn, _item));;
			return _item;
		}
		public IList<proto.entity_photos> All()
		{
			return m_Items.Values;
		}
		public proto.entity_photos Get(long _id)
		{
			return m_Items[_id];
		}
		public bool Exists(long _id)
		{
			return m_Items.ContainsKey(_id);
		}
		public void UpdateSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if (!Exists(_id))
			{
			return;
			}
			var item = Get(_id);
			var cmd = new MySqlCommand("SELECT `id`, `entity_id`, `proto_name`, `guid`, `original`, `thumbnail_small`, `thumbnail_mid`, `thumbnail_large`, `is_main`, `order_number` FROM entity_photos WHERE id = " + _id.ToString());
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					item.DeleteCompositions(Meridian.Default);
					item.DeleteAggregations();
					item.LoadFromReader(reader);
					item.LoadAggregations(_meridian);
					item.LoadCompositions(_meridian);
				}
			}
		}
		public void InsertSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if(Exists(_id)) return;;
			var cmd = new MySqlCommand("SELECT `id`, `entity_id`, `proto_name`, `guid`, `original`, `thumbnail_small`, `thumbnail_mid`, `thumbnail_large`, `is_main`, `order_number` FROM entity_photos WHERE id = " + _id.ToString());
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					var item = new proto.entity_photos();
					item.LoadFromReader(reader);
					item.LoadAggregations(_meridian);
					item.LoadCompositions(_meridian);
					m_Items.Add(item.id, item);
				}
			}
		}
		public void DeleteSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if (!Exists(_id))
			{
			return;
			}
			var item = Get(_id);
			item.DeleteCompositions(Meridian.Default);
			item.DeleteAggregations();
			m_Items.Remove(item.id);
		}
	}
}
