/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;
using MySql.Data.MySqlClient;
using meridian.bewell;
using meridian.bewell.system;

namespace meridian.bewell.protoStore
{
	public partial class field_valuesStore : Meridian.IEntityStore, admin.db.IDataService<proto.field_values>
	{
		public field_valuesStore()
		{
			m_Items = new SortedList<long, proto.field_values>();
		}
		private SortedList<long, proto.field_values> m_Items;
		public void Commit()
		{
			//throw new NotImplementedException();
		}
		public IQueryable<proto.field_values> GetAll()
		{
			return Queryable.AsQueryable<proto.field_values>(All());
		}
		public proto.field_values GetById(long id)
		{
			return Get(id);
		}
		void admin.db.IDataService<proto.field_values>.Insert(proto.field_values item)
		{
			Insert(item);
		}
		void admin.db.IDataService<proto.field_values>.Delete(proto.field_values item)
		{
			Delete(item);
		}
		public proto.field_values CreateItem()
		{
			return new proto.field_values() {   };
		}
		public void AbortItem(proto.field_values item)
		{
			Delete(item);
		}
		public void Discard()
		{
			;
		}
		void admin.db.IDataService<proto.field_values>.Update(proto.field_values item)
		{
			Persist(item);
		}
		public object GetObject(long _id)
		{
			return Get(_id);
		}
		public System.Type GetObjectType()
		{
			return typeof(proto.field_values);
		}
		public void DeleteById(long _id)
		{
			Delete(Get(_id));
		}
		public void UpdateById(long _id)
		{
			Update(Get(_id));
		}
		public void LoadAggregations(Meridian _meridian)
		{
			foreach(var item in m_Items.Values)
			{
				item.LoadAggregations(_meridian);
			}
		}
		public void Select(MySqlConnection _connection)
		{
			var cmd = new MySqlCommand("SELECT `id`, `entity_id`, `proto_name`, `field_id`, `field_value` FROM field_values");
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					var item = new proto.field_values();
					item.LoadFromReader(reader);
					m_Items[item.id] = item;
				}
			}
		}
		public proto.field_values Insert(MySqlConnection _connection, proto.field_values _item)
		{
			var cmd = new MySqlCommand("INSERT INTO field_values ( `entity_id`, `proto_name`, `field_id`, `field_value` ) VALUES ( @entity_id, @proto_name, @field_id, @field_value ); SELECT LAST_INSERT_ID();"); ;
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "entity_id", Value = _item.entity_id });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "proto_name", Value = _item.proto_name });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "field_id", Value = _item.field_id });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "field_value", Value = _item.field_value });
			cmd.Connection = _connection;
			_item.id = Convert.ToInt64(cmd.ExecuteScalar());
			m_Items.Add(_item.id, _item);
			_item.LoadAggregations(Meridian.Default);
			return _item;
		}
		public proto.field_values Update(MySqlConnection _connection, proto.field_values _item)
		{
			bool changed =  false;
			var cmdText =  "";
			var cmd = new MySqlCommand("UPDATE field_values SET `entity_id`= @entity_id, `proto_name`= @proto_name, `field_id`= @field_id, `field_value`= @field_value WHERE id=@id"); ;
			if(_item.mc_id)
			{
			}
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "id", Value = _item.id });
			if(_item.mc_entity_id)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`entity_id` = @entity_id";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "entity_id", Value = _item.entity_id });
			}
			if(_item.mc_proto_name)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`proto_name` = @proto_name";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "proto_name", Value = _item.proto_name != null ? (object)_item.proto_name : DBNull.Value });
			}
			if(_item.mc_field_id)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`field_id` = @field_id";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "field_id", Value = _item.field_id });
			}
			if(_item.mc_field_value)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`field_value` = @field_value";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "field_value", Value = _item.field_value != null ? (object)_item.field_value : DBNull.Value });
			}
			if(changed)
			{
				cmd.CommandText =  "UPDATE field_values SET " + cmdText + " WHERE id=@id";
				cmd.Connection = _connection;
				cmd.ExecuteNonQuery();
				_item.LoadAggregations(Meridian.Default);
			}
			return _item;
		}
		public proto.field_values Delete(MySqlConnection _connection, proto.field_values _item)
		{
			var cmd = new MySqlCommand("DELETE FROM field_values WHERE id=@id"); ;
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "id", Value = _item.id });
			cmd.Connection = _connection;
			cmd.ExecuteScalar();
			return _item;
		}
		public proto.field_values Insert(proto.field_values _item)
		{
			MeridianMonitor.Default.MySqlActionForeground((conn) => Insert(conn, _item));;
			return _item;
		}
		public proto.field_values Persist(proto.field_values _item)
		{
			if(_item.id <= 0)
			{
				_item = Insert(_item);
			}
			_item = Update(_item);
			return _item;
		}
		public proto.field_values Delete(proto.field_values _item)
		{
			_item.DeleteCompositions(Meridian.Default);
			_item.DeleteAggregations();
			m_Items.Remove(_item.id);
			MeridianMonitor.Default.MySqlActionBackground((conn) => Delete(conn, _item));;
			return _item;
		}
		public proto.field_values Update(proto.field_values _item)
		{
			MeridianMonitor.Default.MySqlActionBackground((conn) => Update(conn, _item));;
			return _item;
		}
		public IList<proto.field_values> All()
		{
			return m_Items.Values;
		}
		public proto.field_values Get(long _id)
		{
			return m_Items[_id];
		}
		public bool Exists(long _id)
		{
			return m_Items.ContainsKey(_id);
		}
		public void UpdateSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if (!Exists(_id))
			{
			return;
			}
			var item = Get(_id);
			var cmd = new MySqlCommand("SELECT `id`, `entity_id`, `proto_name`, `field_id`, `field_value` FROM field_values WHERE id = " + _id.ToString());
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					item.DeleteCompositions(Meridian.Default);
					item.DeleteAggregations();
					item.LoadFromReader(reader);
					item.LoadAggregations(_meridian);
					item.LoadCompositions(_meridian);
				}
			}
		}
		public void InsertSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if(Exists(_id)) return;;
			var cmd = new MySqlCommand("SELECT `id`, `entity_id`, `proto_name`, `field_id`, `field_value` FROM field_values WHERE id = " + _id.ToString());
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					var item = new proto.field_values();
					item.LoadFromReader(reader);
					item.LoadAggregations(_meridian);
					item.LoadCompositions(_meridian);
					m_Items.Add(item.id, item);
				}
			}
		}
		public void DeleteSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if (!Exists(_id))
			{
			return;
			}
			var item = Get(_id);
			item.DeleteCompositions(Meridian.Default);
			item.DeleteAggregations();
			m_Items.Remove(item.id);
		}
	}
}
