/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;
using MySql.Data.MySqlClient;
using meridian.bewell;
using meridian.bewell.system;

namespace meridian.bewell.protoStore
{
	public partial class fieldsetsStore : Meridian.IEntityStore, admin.db.IDataService<proto.fieldsets>
	{
		public fieldsetsStore()
		{
			m_Items = new SortedList<long, proto.fieldsets>();
		}
		private SortedList<long, proto.fieldsets> m_Items;
		public void Commit()
		{
			//throw new NotImplementedException();
		}
		public IQueryable<proto.fieldsets> GetAll()
		{
			return Queryable.AsQueryable<proto.fieldsets>(All());
		}
		public proto.fieldsets GetById(long id)
		{
			return Get(id);
		}
		void admin.db.IDataService<proto.fieldsets>.Insert(proto.fieldsets item)
		{
			Insert(item);
		}
		void admin.db.IDataService<proto.fieldsets>.Delete(proto.fieldsets item)
		{
			Delete(item);
		}
		public proto.fieldsets CreateItem()
		{
			return new proto.fieldsets() {   };
		}
		public void AbortItem(proto.fieldsets item)
		{
			Delete(item);
		}
		public void Discard()
		{
			;
		}
		void admin.db.IDataService<proto.fieldsets>.Update(proto.fieldsets item)
		{
			Persist(item);
		}
		public object GetObject(long _id)
		{
			return Get(_id);
		}
		public System.Type GetObjectType()
		{
			return typeof(proto.fieldsets);
		}
		public void DeleteById(long _id)
		{
			Delete(Get(_id));
		}
		public void UpdateById(long _id)
		{
			Update(Get(_id));
		}
		public void LoadAggregations(Meridian _meridian)
		{
			foreach(var item in m_Items.Values)
			{
				item.LoadAggregations(_meridian);
			}
		}
		public void LoadCompositions(Meridian _meridian)
		{
			foreach(var item in m_Items.Values)
			{
				item.LoadCompositions(_meridian);
			}
		}
		public void Select(MySqlConnection _connection)
		{
			var cmd = new MySqlCommand("SELECT `id`, `title`, `url`, `proto_name`, `order_number`, `show_gallery`, `show_map`, `show_in_anounce` FROM fieldsets");
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					var item = new proto.fieldsets();
					item.LoadFromReader(reader);
					m_Items[item.id] = item;
				}
			}
		}
		public proto.fieldsets Insert(MySqlConnection _connection, proto.fieldsets _item)
		{
			var cmd = new MySqlCommand("INSERT INTO fieldsets ( `title`, `url`, `proto_name`, `order_number`, `show_gallery`, `show_map`, `show_in_anounce` ) VALUES ( @title, @url, @proto_name, @order_number, @show_gallery, @show_map, @show_in_anounce ); SELECT LAST_INSERT_ID();"); ;
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "title", Value = _item.title });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "url", Value = _item.url });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "proto_name", Value = _item.proto_name });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "order_number", Value = _item.order_number });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "show_gallery", Value = _item.show_gallery });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "show_map", Value = _item.show_map });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "show_in_anounce", Value = _item.show_in_anounce });
			cmd.Connection = _connection;
			_item.id = Convert.ToInt64(cmd.ExecuteScalar());
			m_Items.Add(_item.id, _item);
			_item.LoadAggregations(Meridian.Default);
			return _item;
		}
		public proto.fieldsets Update(MySqlConnection _connection, proto.fieldsets _item)
		{
			bool changed =  false;
			var cmdText =  "";
			var cmd = new MySqlCommand("UPDATE fieldsets SET `title`= @title, `url`= @url, `proto_name`= @proto_name, `order_number`= @order_number, `show_gallery`= @show_gallery, `show_map`= @show_map, `show_in_anounce`= @show_in_anounce WHERE id=@id"); ;
			if(_item.mc_id)
			{
			}
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "id", Value = _item.id });
			if(_item.mc_title)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`title` = @title";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "title", Value = _item.title != null ? (object)_item.title : DBNull.Value });
			}
			if(_item.mc_url)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`url` = @url";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "url", Value = _item.url != null ? (object)_item.url : DBNull.Value });
			}
			if(_item.mc_proto_name)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`proto_name` = @proto_name";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "proto_name", Value = _item.proto_name != null ? (object)_item.proto_name : DBNull.Value });
			}
			if(_item.mc_order_number)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`order_number` = @order_number";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "order_number", Value = _item.order_number });
			}
			if(_item.mc_show_gallery)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`show_gallery` = @show_gallery";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "show_gallery", Value = _item.show_gallery });
			}
			if(_item.mc_show_map)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`show_map` = @show_map";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "show_map", Value = _item.show_map });
			}
			if(_item.mc_show_in_anounce)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`show_in_anounce` = @show_in_anounce";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "show_in_anounce", Value = _item.show_in_anounce });
			}
			if(changed)
			{
				cmd.CommandText =  "UPDATE fieldsets SET " + cmdText + " WHERE id=@id";
				cmd.Connection = _connection;
				cmd.ExecuteNonQuery();
				_item.LoadAggregations(Meridian.Default);
			}
			return _item;
		}
		public proto.fieldsets Delete(MySqlConnection _connection, proto.fieldsets _item)
		{
			var cmd = new MySqlCommand("DELETE FROM fieldsets WHERE id=@id"); ;
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "id", Value = _item.id });
			cmd.Connection = _connection;
			cmd.ExecuteScalar();
			return _item;
		}
		public proto.fieldsets Insert(proto.fieldsets _item)
		{
			MeridianMonitor.Default.MySqlActionForeground((conn) => Insert(conn, _item));;
			return _item;
		}
		public proto.fieldsets Persist(proto.fieldsets _item)
		{
			if(_item.id <= 0)
			{
				_item = Insert(_item);
			}
			_item = Update(_item);
			return _item;
		}
		public proto.fieldsets Delete(proto.fieldsets _item)
		{
			_item.DeleteCompositions(Meridian.Default);
			_item.DeleteAggregations();
			m_Items.Remove(_item.id);
			MeridianMonitor.Default.MySqlActionBackground((conn) => Delete(conn, _item));;
			return _item;
		}
		public proto.fieldsets Update(proto.fieldsets _item)
		{
			MeridianMonitor.Default.MySqlActionBackground((conn) => Update(conn, _item));;
			return _item;
		}
		public IList<proto.fieldsets> All()
		{
			return m_Items.Values;
		}
		public proto.fieldsets Get(long _id)
		{
			return m_Items[_id];
		}
		public bool Exists(long _id)
		{
			return m_Items.ContainsKey(_id);
		}
		public void UpdateSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if (!Exists(_id))
			{
			return;
			}
			var item = Get(_id);
			var cmd = new MySqlCommand("SELECT `id`, `title`, `url`, `proto_name`, `order_number`, `show_gallery`, `show_map`, `show_in_anounce` FROM fieldsets WHERE id = " + _id.ToString());
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					item.DeleteCompositions(Meridian.Default);
					item.DeleteAggregations();
					item.LoadFromReader(reader);
					item.LoadAggregations(_meridian);
					item.LoadCompositions(_meridian);
				}
			}
		}
		public void InsertSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if(Exists(_id)) return;;
			var cmd = new MySqlCommand("SELECT `id`, `title`, `url`, `proto_name`, `order_number`, `show_gallery`, `show_map`, `show_in_anounce` FROM fieldsets WHERE id = " + _id.ToString());
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					var item = new proto.fieldsets();
					item.LoadFromReader(reader);
					item.LoadAggregations(_meridian);
					item.LoadCompositions(_meridian);
					m_Items.Add(item.id, item);
				}
			}
		}
		public void DeleteSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if (!Exists(_id))
			{
			return;
			}
			var item = Get(_id);
			item.DeleteCompositions(Meridian.Default);
			item.DeleteAggregations();
			m_Items.Remove(item.id);
		}
	}
}
