/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;
using MySql.Data.MySqlClient;
using meridian.bewell;
using meridian.bewell.system;

namespace meridian.bewell.protoStore
{
	public partial class hotelsStore : Meridian.IEntityStore, admin.db.IDataService<proto.hotels>
	{
		public hotelsStore()
		{
			m_Items = new SortedList<long, proto.hotels>();
		}
		private SortedList<long, proto.hotels> m_Items;
		public void Commit()
		{
			//throw new NotImplementedException();
		}
		public IQueryable<proto.hotels> GetAll()
		{
			return Queryable.AsQueryable<proto.hotels>(All());
		}
		public proto.hotels GetById(long id)
		{
			return Get(id);
		}
		void admin.db.IDataService<proto.hotels>.Insert(proto.hotels item)
		{
			Insert(item);
		}
		void admin.db.IDataService<proto.hotels>.Delete(proto.hotels item)
		{
			Delete(item);
		}
		public proto.hotels CreateItem()
		{
			return new proto.hotels() {   };
		}
		public void AbortItem(proto.hotels item)
		{
			Delete(item);
		}
		public void Discard()
		{
			;
		}
		void admin.db.IDataService<proto.hotels>.Update(proto.hotels item)
		{
			Persist(item);
		}
		public object GetObject(long _id)
		{
			return Get(_id);
		}
		public System.Type GetObjectType()
		{
			return typeof(proto.hotels);
		}
		public void DeleteById(long _id)
		{
			Delete(Get(_id));
		}
		public void UpdateById(long _id)
		{
			Update(Get(_id));
		}
		public void LoadAggregations(Meridian _meridian)
		{
			foreach(var item in m_Items.Values)
			{
				item.LoadAggregations(_meridian);
			}
		}
		public void LoadCompositions(Meridian _meridian)
		{
			foreach(var item in m_Items.Values)
			{
				item.LoadCompositions(_meridian);
			}
		}
		public void Select(MySqlConnection _connection)
		{
			var cmd = new MySqlCommand("SELECT `id`, `title`, `stars`, `class_id`, `coordinates`, `is_recomended_main_page`, `is_recomended`, `deseases`, `treatment_options`, `properties`, `resort_id`, `noyayesgo`, `is_published` FROM hotels");
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					var item = new proto.hotels();
					item.LoadFromReader(reader);
					m_Items[item.id] = item;
				}
			}
		}
		public proto.hotels Insert(MySqlConnection _connection, proto.hotels _item)
		{
			var cmd = new MySqlCommand("INSERT INTO hotels ( `title`, `stars`, `class_id`, `coordinates`, `is_recomended_main_page`, `is_recomended`, `deseases`, `treatment_options`, `properties`, `resort_id`, `noyayesgo`, `is_published` ) VALUES ( @title, @stars, @class_id, @coordinates, @is_recomended_main_page, @is_recomended, @deseases, @treatment_options, @properties, @resort_id, @noyayesgo, @is_published ); SELECT LAST_INSERT_ID();"); ;
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "title", Value = _item.title });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "stars", Value = _item.stars });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "class_id", Value = _item.class_id });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "coordinates", Value = _item.coordinates });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "is_recomended_main_page", Value = _item.is_recomended_main_page });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "is_recomended", Value = _item.is_recomended });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "deseases", Value = _item.deseases });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "treatment_options", Value = _item.treatment_options });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "properties", Value = _item.properties });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "resort_id", Value = _item.resort_id });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "noyayesgo", Value = _item.noyayesgo });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "is_published", Value = _item.is_published });
			cmd.Connection = _connection;
			_item.id = Convert.ToInt64(cmd.ExecuteScalar());
			m_Items.Add(_item.id, _item);
			_item.LoadAggregations(Meridian.Default);
			return _item;
		}
		public proto.hotels Update(MySqlConnection _connection, proto.hotels _item)
		{
			bool changed =  false;
			var cmdText =  "";
			var cmd = new MySqlCommand("UPDATE hotels SET `title`= @title, `stars`= @stars, `class_id`= @class_id, `coordinates`= @coordinates, `is_recomended_main_page`= @is_recomended_main_page, `is_recomended`= @is_recomended, `deseases`= @deseases, `treatment_options`= @treatment_options, `properties`= @properties, `resort_id`= @resort_id, `noyayesgo`= @noyayesgo, `is_published`= @is_published WHERE id=@id"); ;
			if(_item.mc_id)
			{
			}
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "id", Value = _item.id });
			if(_item.mc_title)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`title` = @title";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "title", Value = _item.title != null ? (object)_item.title : DBNull.Value });
			}
			if(_item.mc_stars)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`stars` = @stars";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "stars", Value = _item.stars });
			}
			if(_item.mc_class_id)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`class_id` = @class_id";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "class_id", Value = _item.class_id });
			}
			if(_item.mc_coordinates)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`coordinates` = @coordinates";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "coordinates", Value = _item.coordinates != null ? (object)_item.coordinates : DBNull.Value });
			}
			if(_item.mc_is_recomended_main_page)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`is_recomended_main_page` = @is_recomended_main_page";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "is_recomended_main_page", Value = _item.is_recomended_main_page });
			}
			if(_item.mc_is_recomended)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`is_recomended` = @is_recomended";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "is_recomended", Value = _item.is_recomended });
			}
			if(_item.mc_deseases)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`deseases` = @deseases";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "deseases", Value = _item.deseases != null ? (object)_item.deseases : DBNull.Value });
			}
			if(_item.mc_treatment_options)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`treatment_options` = @treatment_options";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "treatment_options", Value = _item.treatment_options != null ? (object)_item.treatment_options : DBNull.Value });
			}
			if(_item.mc_properties)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`properties` = @properties";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "properties", Value = _item.properties != null ? (object)_item.properties : DBNull.Value });
			}
			if(_item.mc_resort_id)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`resort_id` = @resort_id";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "resort_id", Value = _item.resort_id });
			}
			if(_item.mc_noyayesgo)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`noyayesgo` = @noyayesgo";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "noyayesgo", Value = _item.noyayesgo });
			}
			if(_item.mc_is_published)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`is_published` = @is_published";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "is_published", Value = _item.is_published });
			}
			if(changed)
			{
				cmd.CommandText =  "UPDATE hotels SET " + cmdText + " WHERE id=@id";
				cmd.Connection = _connection;
				cmd.ExecuteNonQuery();
				_item.LoadAggregations(Meridian.Default);
			}
			return _item;
		}
		public proto.hotels Delete(MySqlConnection _connection, proto.hotels _item)
		{
			var cmd = new MySqlCommand("DELETE FROM hotels WHERE id=@id"); ;
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "id", Value = _item.id });
			cmd.Connection = _connection;
			cmd.ExecuteScalar();
			return _item;
		}
		public proto.hotels Insert(proto.hotels _item)
		{
			MeridianMonitor.Default.MySqlActionForeground((conn) => Insert(conn, _item));;
			return _item;
		}
		public proto.hotels Persist(proto.hotels _item)
		{
			if(_item.id <= 0)
			{
				_item = Insert(_item);
			}
			_item = Update(_item);
			return _item;
		}
		public proto.hotels Delete(proto.hotels _item)
		{
			_item.DeleteCompositions(Meridian.Default);
			_item.DeleteAggregations();
			m_Items.Remove(_item.id);
			MeridianMonitor.Default.MySqlActionBackground((conn) => Delete(conn, _item));;
			return _item;
		}
		public proto.hotels Update(proto.hotels _item)
		{
			MeridianMonitor.Default.MySqlActionBackground((conn) => Update(conn, _item));;
			return _item;
		}
		public IList<proto.hotels> All()
		{
			return m_Items.Values;
		}
		public proto.hotels Get(long _id)
		{
			return m_Items[_id];
		}
		public bool Exists(long _id)
		{
			return m_Items.ContainsKey(_id);
		}
		public void UpdateSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if (!Exists(_id))
			{
			return;
			}
			var item = Get(_id);
			var cmd = new MySqlCommand("SELECT `id`, `title`, `stars`, `class_id`, `coordinates`, `is_recomended_main_page`, `is_recomended`, `deseases`, `treatment_options`, `properties`, `resort_id`, `noyayesgo`, `is_published` FROM hotels WHERE id = " + _id.ToString());
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					item.DeleteCompositions(Meridian.Default);
					item.DeleteAggregations();
					item.LoadFromReader(reader);
					item.LoadAggregations(_meridian);
					item.LoadCompositions(_meridian);
				}
			}
		}
		public void InsertSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if(Exists(_id)) return;;
			var cmd = new MySqlCommand("SELECT `id`, `title`, `stars`, `class_id`, `coordinates`, `is_recomended_main_page`, `is_recomended`, `deseases`, `treatment_options`, `properties`, `resort_id`, `noyayesgo`, `is_published` FROM hotels WHERE id = " + _id.ToString());
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					var item = new proto.hotels();
					item.LoadFromReader(reader);
					item.LoadAggregations(_meridian);
					item.LoadCompositions(_meridian);
					m_Items.Add(item.id, item);
				}
			}
		}
		public void DeleteSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if (!Exists(_id))
			{
			return;
			}
			var item = Get(_id);
			item.DeleteCompositions(Meridian.Default);
			item.DeleteAggregations();
			m_Items.Remove(item.id);
		}
	}
}
