/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;
using MySql.Data.MySqlClient;
using meridian.bewell;
using meridian.bewell.system;

namespace meridian.bewell.protoStore
{
	public partial class pricesStore : Meridian.IEntityStore, admin.db.IDataService<proto.prices>
	{
		public pricesStore()
		{
			m_Items = new SortedList<long, proto.prices>();
		}
		private SortedList<long, proto.prices> m_Items;
		public void Commit()
		{
			//throw new NotImplementedException();
		}
		public IQueryable<proto.prices> GetAll()
		{
			return Queryable.AsQueryable<proto.prices>(All());
		}
		public proto.prices GetById(long id)
		{
			return Get(id);
		}
		void admin.db.IDataService<proto.prices>.Insert(proto.prices item)
		{
			Insert(item);
		}
		void admin.db.IDataService<proto.prices>.Delete(proto.prices item)
		{
			Delete(item);
		}
		public proto.prices CreateItem()
		{
			return new proto.prices() {   };
		}
		public void AbortItem(proto.prices item)
		{
			Delete(item);
		}
		public void Discard()
		{
			;
		}
		void admin.db.IDataService<proto.prices>.Update(proto.prices item)
		{
			Persist(item);
		}
		public object GetObject(long _id)
		{
			return Get(_id);
		}
		public System.Type GetObjectType()
		{
			return typeof(proto.prices);
		}
		public void DeleteById(long _id)
		{
			Delete(Get(_id));
		}
		public void UpdateById(long _id)
		{
			Update(Get(_id));
		}
		public void LoadAggregations(Meridian _meridian)
		{
			foreach(var item in m_Items.Values)
			{
				item.LoadAggregations(_meridian);
			}
		}
		public void Select(MySqlConnection _connection)
		{
			var cmd = new MySqlCommand("SELECT `id`, `entity_id`, `proto_name`, `month`, `price`, `comment` FROM prices");
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					var item = new proto.prices();
					item.LoadFromReader(reader);
					m_Items[item.id] = item;
				}
			}
		}
		public proto.prices Insert(MySqlConnection _connection, proto.prices _item)
		{
			var cmd = new MySqlCommand("INSERT INTO prices ( `entity_id`, `proto_name`, `month`, `price`, `comment` ) VALUES ( @entity_id, @proto_name, @month, @price, @comment ); SELECT LAST_INSERT_ID();"); ;
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "entity_id", Value = _item.entity_id });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "proto_name", Value = _item.proto_name });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "month", Value = _item.month });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "price", Value = _item.price });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "comment", Value = _item.comment });
			cmd.Connection = _connection;
			_item.id = Convert.ToInt64(cmd.ExecuteScalar());
			m_Items.Add(_item.id, _item);
			_item.LoadAggregations(Meridian.Default);
			return _item;
		}
		public proto.prices Update(MySqlConnection _connection, proto.prices _item)
		{
			bool changed =  false;
			var cmdText =  "";
			var cmd = new MySqlCommand("UPDATE prices SET `entity_id`= @entity_id, `proto_name`= @proto_name, `month`= @month, `price`= @price, `comment`= @comment WHERE id=@id"); ;
			if(_item.mc_id)
			{
			}
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "id", Value = _item.id });
			if(_item.mc_entity_id)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`entity_id` = @entity_id";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "entity_id", Value = _item.entity_id });
			}
			if(_item.mc_proto_name)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`proto_name` = @proto_name";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "proto_name", Value = _item.proto_name != null ? (object)_item.proto_name : DBNull.Value });
			}
			if(_item.mc_month)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`month` = @month";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "month", Value = _item.month });
			}
			if(_item.mc_price)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`price` = @price";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "price", Value = _item.price });
			}
			if(_item.mc_comment)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`comment` = @comment";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "comment", Value = _item.comment != null ? (object)_item.comment : DBNull.Value });
			}
			if(changed)
			{
				cmd.CommandText =  "UPDATE prices SET " + cmdText + " WHERE id=@id";
				cmd.Connection = _connection;
				cmd.ExecuteNonQuery();
				_item.LoadAggregations(Meridian.Default);
			}
			return _item;
		}
		public proto.prices Delete(MySqlConnection _connection, proto.prices _item)
		{
			var cmd = new MySqlCommand("DELETE FROM prices WHERE id=@id"); ;
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "id", Value = _item.id });
			cmd.Connection = _connection;
			cmd.ExecuteScalar();
			return _item;
		}
		public proto.prices Insert(proto.prices _item)
		{
			MeridianMonitor.Default.MySqlActionForeground((conn) => Insert(conn, _item));;
			return _item;
		}
		public proto.prices Persist(proto.prices _item)
		{
			if(_item.id <= 0)
			{
				_item = Insert(_item);
			}
			_item = Update(_item);
			return _item;
		}
		public proto.prices Delete(proto.prices _item)
		{
			_item.DeleteCompositions(Meridian.Default);
			_item.DeleteAggregations();
			m_Items.Remove(_item.id);
			MeridianMonitor.Default.MySqlActionBackground((conn) => Delete(conn, _item));;
			return _item;
		}
		public proto.prices Update(proto.prices _item)
		{
			MeridianMonitor.Default.MySqlActionBackground((conn) => Update(conn, _item));;
			return _item;
		}
		public IList<proto.prices> All()
		{
			return m_Items.Values;
		}
		public proto.prices Get(long _id)
		{
			return m_Items[_id];
		}
		public bool Exists(long _id)
		{
			return m_Items.ContainsKey(_id);
		}
		public void UpdateSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if (!Exists(_id))
			{
			return;
			}
			var item = Get(_id);
			var cmd = new MySqlCommand("SELECT `id`, `entity_id`, `proto_name`, `month`, `price`, `comment` FROM prices WHERE id = " + _id.ToString());
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					item.DeleteCompositions(Meridian.Default);
					item.DeleteAggregations();
					item.LoadFromReader(reader);
					item.LoadAggregations(_meridian);
					item.LoadCompositions(_meridian);
				}
			}
		}
		public void InsertSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if(Exists(_id)) return;;
			var cmd = new MySqlCommand("SELECT `id`, `entity_id`, `proto_name`, `month`, `price`, `comment` FROM prices WHERE id = " + _id.ToString());
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					var item = new proto.prices();
					item.LoadFromReader(reader);
					item.LoadAggregations(_meridian);
					item.LoadCompositions(_meridian);
					m_Items.Add(item.id, item);
				}
			}
		}
		public void DeleteSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if (!Exists(_id))
			{
			return;
			}
			var item = Get(_id);
			item.DeleteCompositions(Meridian.Default);
			item.DeleteAggregations();
			m_Items.Remove(item.id);
		}
	}
}
