/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;
using MySql.Data.MySqlClient;
using meridian.bewell;
using meridian.bewell.system;

namespace meridian.bewell.protoStore
{
	public partial class questionsStore : Meridian.IEntityStore, admin.db.IDataService<proto.questions>
	{
		public questionsStore()
		{
			m_Items = new SortedList<long, proto.questions>();
		}
		private SortedList<long, proto.questions> m_Items;
		public void Commit()
		{
			//throw new NotImplementedException();
		}
		public IQueryable<proto.questions> GetAll()
		{
			return Queryable.AsQueryable<proto.questions>(All());
		}
		public proto.questions GetById(long id)
		{
			return Get(id);
		}
		void admin.db.IDataService<proto.questions>.Insert(proto.questions item)
		{
			Insert(item);
		}
		void admin.db.IDataService<proto.questions>.Delete(proto.questions item)
		{
			Delete(item);
		}
		public proto.questions CreateItem()
		{
			return new proto.questions() {   };
		}
		public void AbortItem(proto.questions item)
		{
			Delete(item);
		}
		public void Discard()
		{
			;
		}
		void admin.db.IDataService<proto.questions>.Update(proto.questions item)
		{
			Persist(item);
		}
		public object GetObject(long _id)
		{
			return Get(_id);
		}
		public System.Type GetObjectType()
		{
			return typeof(proto.questions);
		}
		public void DeleteById(long _id)
		{
			Delete(Get(_id));
		}
		public void UpdateById(long _id)
		{
			Update(Get(_id));
		}
		public void LoadAggregations(Meridian _meridian)
		{
			foreach(var item in m_Items.Values)
			{
				item.LoadAggregations(_meridian);
			}
		}
		public void Select(MySqlConnection _connection)
		{
			var cmd = new MySqlCommand("SELECT `id`, `account_id`, `ask_date`, `asking_user_name`, `asking_user_email`, `question`, `replier_account_id`, `reply_text` FROM questions");
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					var item = new proto.questions();
					item.LoadFromReader(reader);
					m_Items[item.id] = item;
				}
			}
		}
		public proto.questions Insert(MySqlConnection _connection, proto.questions _item)
		{
			var cmd = new MySqlCommand("INSERT INTO questions ( `account_id`, `ask_date`, `asking_user_name`, `asking_user_email`, `question`, `replier_account_id`, `reply_text` ) VALUES ( @account_id, @ask_date, @asking_user_name, @asking_user_email, @question, @replier_account_id, @reply_text ); SELECT LAST_INSERT_ID();"); ;
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "account_id", Value = _item.account_id });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "ask_date", Value = (_item.ask_date != null && _item.ask_date.Year > 1800) ? _item.ask_date : new DateTime(1800, 1, 1) });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "asking_user_name", Value = _item.asking_user_name });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "asking_user_email", Value = _item.asking_user_email });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "question", Value = _item.question });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "replier_account_id", Value = _item.replier_account_id });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "reply_text", Value = _item.reply_text });
			cmd.Connection = _connection;
			_item.id = Convert.ToInt64(cmd.ExecuteScalar());
			m_Items.Add(_item.id, _item);
			_item.LoadAggregations(Meridian.Default);
			return _item;
		}
		public proto.questions Update(MySqlConnection _connection, proto.questions _item)
		{
			bool changed =  false;
			var cmdText =  "";
			var cmd = new MySqlCommand("UPDATE questions SET `account_id`= @account_id, `ask_date`= @ask_date, `asking_user_name`= @asking_user_name, `asking_user_email`= @asking_user_email, `question`= @question, `replier_account_id`= @replier_account_id, `reply_text`= @reply_text WHERE id=@id"); ;
			if(_item.mc_id)
			{
			}
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "id", Value = _item.id });
			if(_item.mc_account_id)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`account_id` = @account_id";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "account_id", Value = _item.account_id });
			}
			if(_item.mc_ask_date)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`ask_date` = @ask_date";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "ask_date", Value = (_item.ask_date != null && _item.ask_date.Year > 1800) ? _item.ask_date : new DateTime(1800, 1, 1) });
			}
			if(_item.mc_asking_user_name)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`asking_user_name` = @asking_user_name";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "asking_user_name", Value = _item.asking_user_name != null ? (object)_item.asking_user_name : DBNull.Value });
			}
			if(_item.mc_asking_user_email)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`asking_user_email` = @asking_user_email";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "asking_user_email", Value = _item.asking_user_email != null ? (object)_item.asking_user_email : DBNull.Value });
			}
			if(_item.mc_question)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`question` = @question";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "question", Value = _item.question != null ? (object)_item.question : DBNull.Value });
			}
			if(_item.mc_replier_account_id)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`replier_account_id` = @replier_account_id";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "replier_account_id", Value = _item.replier_account_id });
			}
			if(_item.mc_reply_text)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`reply_text` = @reply_text";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "reply_text", Value = _item.reply_text != null ? (object)_item.reply_text : DBNull.Value });
			}
			if(changed)
			{
				cmd.CommandText =  "UPDATE questions SET " + cmdText + " WHERE id=@id";
				cmd.Connection = _connection;
				cmd.ExecuteNonQuery();
				_item.LoadAggregations(Meridian.Default);
			}
			return _item;
		}
		public proto.questions Delete(MySqlConnection _connection, proto.questions _item)
		{
			var cmd = new MySqlCommand("DELETE FROM questions WHERE id=@id"); ;
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "id", Value = _item.id });
			cmd.Connection = _connection;
			cmd.ExecuteScalar();
			return _item;
		}
		public proto.questions Insert(proto.questions _item)
		{
			MeridianMonitor.Default.MySqlActionForeground((conn) => Insert(conn, _item));;
			return _item;
		}
		public proto.questions Persist(proto.questions _item)
		{
			if(_item.id <= 0)
			{
				_item = Insert(_item);
			}
			_item = Update(_item);
			return _item;
		}
		public proto.questions Delete(proto.questions _item)
		{
			_item.DeleteCompositions(Meridian.Default);
			_item.DeleteAggregations();
			m_Items.Remove(_item.id);
			MeridianMonitor.Default.MySqlActionBackground((conn) => Delete(conn, _item));;
			return _item;
		}
		public proto.questions Update(proto.questions _item)
		{
			MeridianMonitor.Default.MySqlActionBackground((conn) => Update(conn, _item));;
			return _item;
		}
		public IList<proto.questions> All()
		{
			return m_Items.Values;
		}
		public proto.questions Get(long _id)
		{
			return m_Items[_id];
		}
		public bool Exists(long _id)
		{
			return m_Items.ContainsKey(_id);
		}
		public void UpdateSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if (!Exists(_id))
			{
			return;
			}
			var item = Get(_id);
			var cmd = new MySqlCommand("SELECT `id`, `account_id`, `ask_date`, `asking_user_name`, `asking_user_email`, `question`, `replier_account_id`, `reply_text` FROM questions WHERE id = " + _id.ToString());
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					item.DeleteCompositions(Meridian.Default);
					item.DeleteAggregations();
					item.LoadFromReader(reader);
					item.LoadAggregations(_meridian);
					item.LoadCompositions(_meridian);
				}
			}
		}
		public void InsertSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if(Exists(_id)) return;;
			var cmd = new MySqlCommand("SELECT `id`, `account_id`, `ask_date`, `asking_user_name`, `asking_user_email`, `question`, `replier_account_id`, `reply_text` FROM questions WHERE id = " + _id.ToString());
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					var item = new proto.questions();
					item.LoadFromReader(reader);
					item.LoadAggregations(_meridian);
					item.LoadCompositions(_meridian);
					m_Items.Add(item.id, item);
				}
			}
		}
		public void DeleteSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if (!Exists(_id))
			{
			return;
			}
			var item = Get(_id);
			item.DeleteCompositions(Meridian.Default);
			item.DeleteAggregations();
			m_Items.Remove(item.id);
		}
	}
}
