/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;
using MySql.Data.MySqlClient;
using meridian.bewell;
using meridian.bewell.system;

namespace meridian.bewell.protoStore
{
	public partial class resort_zonesStore : Meridian.IEntityStore, admin.db.IDataService<proto.resort_zones>
	{
		public resort_zonesStore()
		{
			m_Items = new SortedList<long, proto.resort_zones>();
		}
		private SortedList<long, proto.resort_zones> m_Items;
		public void Commit()
		{
			//throw new NotImplementedException();
		}
		public IQueryable<proto.resort_zones> GetAll()
		{
			return Queryable.AsQueryable<proto.resort_zones>(All());
		}
		public proto.resort_zones GetById(long id)
		{
			return Get(id);
		}
		void admin.db.IDataService<proto.resort_zones>.Insert(proto.resort_zones item)
		{
			Insert(item);
		}
		void admin.db.IDataService<proto.resort_zones>.Delete(proto.resort_zones item)
		{
			Delete(item);
		}
		public proto.resort_zones CreateItem()
		{
			return new proto.resort_zones() {   };
		}
		public void AbortItem(proto.resort_zones item)
		{
			Delete(item);
		}
		public void Discard()
		{
			;
		}
		void admin.db.IDataService<proto.resort_zones>.Update(proto.resort_zones item)
		{
			Persist(item);
		}
		public object GetObject(long _id)
		{
			return Get(_id);
		}
		public System.Type GetObjectType()
		{
			return typeof(proto.resort_zones);
		}
		public void DeleteById(long _id)
		{
			Delete(Get(_id));
		}
		public void UpdateById(long _id)
		{
			Update(Get(_id));
		}
		public void LoadAggregations(Meridian _meridian)
		{
			foreach(var item in m_Items.Values)
			{
				item.LoadAggregations(_meridian);
			}
		}
		public void Select(MySqlConnection _connection)
		{
			var cmd = new MySqlCommand("SELECT `id`, `title`, `territory_id`, `health_factors`, `treatment_options` FROM resort_zones");
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					var item = new proto.resort_zones();
					item.LoadFromReader(reader);
					m_Items[item.id] = item;
				}
			}
		}
		public proto.resort_zones Insert(MySqlConnection _connection, proto.resort_zones _item)
		{
			var cmd = new MySqlCommand("INSERT INTO resort_zones ( `title`, `territory_id`, `health_factors`, `treatment_options` ) VALUES ( @title, @territory_id, @health_factors, @treatment_options ); SELECT LAST_INSERT_ID();"); ;
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "title", Value = _item.title });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "territory_id", Value = _item.territory_id });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "health_factors", Value = _item.health_factors });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "treatment_options", Value = _item.treatment_options });
			cmd.Connection = _connection;
			_item.id = Convert.ToInt64(cmd.ExecuteScalar());
			m_Items.Add(_item.id, _item);
			_item.LoadAggregations(Meridian.Default);
			return _item;
		}
		public proto.resort_zones Update(MySqlConnection _connection, proto.resort_zones _item)
		{
			bool changed =  false;
			var cmdText =  "";
			var cmd = new MySqlCommand("UPDATE resort_zones SET `title`= @title, `territory_id`= @territory_id, `health_factors`= @health_factors, `treatment_options`= @treatment_options WHERE id=@id"); ;
			if(_item.mc_id)
			{
			}
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "id", Value = _item.id });
			if(_item.mc_title)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`title` = @title";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "title", Value = _item.title != null ? (object)_item.title : DBNull.Value });
			}
			if(_item.mc_territory_id)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`territory_id` = @territory_id";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "territory_id", Value = _item.territory_id });
			}
			if(_item.mc_health_factors)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`health_factors` = @health_factors";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "health_factors", Value = _item.health_factors != null ? (object)_item.health_factors : DBNull.Value });
			}
			if(_item.mc_treatment_options)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`treatment_options` = @treatment_options";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "treatment_options", Value = _item.treatment_options != null ? (object)_item.treatment_options : DBNull.Value });
			}
			if(changed)
			{
				cmd.CommandText =  "UPDATE resort_zones SET " + cmdText + " WHERE id=@id";
				cmd.Connection = _connection;
				cmd.ExecuteNonQuery();
				_item.LoadAggregations(Meridian.Default);
			}
			return _item;
		}
		public proto.resort_zones Delete(MySqlConnection _connection, proto.resort_zones _item)
		{
			var cmd = new MySqlCommand("DELETE FROM resort_zones WHERE id=@id"); ;
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "id", Value = _item.id });
			cmd.Connection = _connection;
			cmd.ExecuteScalar();
			return _item;
		}
		public proto.resort_zones Insert(proto.resort_zones _item)
		{
			MeridianMonitor.Default.MySqlActionForeground((conn) => Insert(conn, _item));;
			return _item;
		}
		public proto.resort_zones Persist(proto.resort_zones _item)
		{
			if(_item.id <= 0)
			{
				_item = Insert(_item);
			}
			_item = Update(_item);
			return _item;
		}
		public proto.resort_zones Delete(proto.resort_zones _item)
		{
			_item.DeleteCompositions(Meridian.Default);
			_item.DeleteAggregations();
			m_Items.Remove(_item.id);
			MeridianMonitor.Default.MySqlActionBackground((conn) => Delete(conn, _item));;
			return _item;
		}
		public proto.resort_zones Update(proto.resort_zones _item)
		{
			MeridianMonitor.Default.MySqlActionBackground((conn) => Update(conn, _item));;
			return _item;
		}
		public IList<proto.resort_zones> All()
		{
			return m_Items.Values;
		}
		public proto.resort_zones Get(long _id)
		{
			return m_Items[_id];
		}
		public bool Exists(long _id)
		{
			return m_Items.ContainsKey(_id);
		}
		public void UpdateSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if (!Exists(_id))
			{
			return;
			}
			var item = Get(_id);
			var cmd = new MySqlCommand("SELECT `id`, `title`, `territory_id`, `health_factors`, `treatment_options` FROM resort_zones WHERE id = " + _id.ToString());
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					item.DeleteCompositions(Meridian.Default);
					item.DeleteAggregations();
					item.LoadFromReader(reader);
					item.LoadAggregations(_meridian);
					item.LoadCompositions(_meridian);
				}
			}
		}
		public void InsertSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if(Exists(_id)) return;;
			var cmd = new MySqlCommand("SELECT `id`, `title`, `territory_id`, `health_factors`, `treatment_options` FROM resort_zones WHERE id = " + _id.ToString());
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					var item = new proto.resort_zones();
					item.LoadFromReader(reader);
					item.LoadAggregations(_meridian);
					item.LoadCompositions(_meridian);
					m_Items.Add(item.id, item);
				}
			}
		}
		public void DeleteSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if (!Exists(_id))
			{
			return;
			}
			var item = Get(_id);
			item.DeleteCompositions(Meridian.Default);
			item.DeleteAggregations();
			m_Items.Remove(item.id);
		}
	}
}
