/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;
using MySql.Data.MySqlClient;
using meridian.bewell;
using meridian.bewell.system;

namespace meridian.bewell.protoStore
{
	public partial class seo_metadataStore : Meridian.IEntityStore, admin.db.IDataService<proto.seo_metadata>
	{
		public seo_metadataStore()
		{
			m_Items = new SortedList<long, proto.seo_metadata>();
		}
		private SortedList<long, proto.seo_metadata> m_Items;
		public void Commit()
		{
			//throw new NotImplementedException();
		}
		public IQueryable<proto.seo_metadata> GetAll()
		{
			return Queryable.AsQueryable<proto.seo_metadata>(All());
		}
		public proto.seo_metadata GetById(long id)
		{
			return Get(id);
		}
		void admin.db.IDataService<proto.seo_metadata>.Insert(proto.seo_metadata item)
		{
			Insert(item);
		}
		void admin.db.IDataService<proto.seo_metadata>.Delete(proto.seo_metadata item)
		{
			Delete(item);
		}
		public proto.seo_metadata CreateItem()
		{
			return new proto.seo_metadata() {   };
		}
		public void AbortItem(proto.seo_metadata item)
		{
			Delete(item);
		}
		public void Discard()
		{
			;
		}
		void admin.db.IDataService<proto.seo_metadata>.Update(proto.seo_metadata item)
		{
			Persist(item);
		}
		public object GetObject(long _id)
		{
			return Get(_id);
		}
		public System.Type GetObjectType()
		{
			return typeof(proto.seo_metadata);
		}
		public void DeleteById(long _id)
		{
			Delete(Get(_id));
		}
		public void UpdateById(long _id)
		{
			Update(Get(_id));
		}
		public void LoadAggregations(Meridian _meridian)
		{
			foreach(var item in m_Items.Values)
			{
				item.LoadAggregations(_meridian);
			}
		}
		public void Select(MySqlConnection _connection)
		{
			var cmd = new MySqlCommand("SELECT `id`, `entity_id`, `proto_name`, `url`, `title`, `keywords`, `description` FROM seo_metadata");
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					var item = new proto.seo_metadata();
					item.LoadFromReader(reader);
					m_Items[item.id] = item;
				}
			}
		}
		public proto.seo_metadata Insert(MySqlConnection _connection, proto.seo_metadata _item)
		{
			var cmd = new MySqlCommand("INSERT INTO seo_metadata ( `entity_id`, `proto_name`, `url`, `title`, `keywords`, `description` ) VALUES ( @entity_id, @proto_name, @url, @title, @keywords, @description ); SELECT LAST_INSERT_ID();"); ;
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "entity_id", Value = _item.entity_id });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "proto_name", Value = _item.proto_name });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "url", Value = _item.url });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "title", Value = _item.title });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "keywords", Value = _item.keywords });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "description", Value = _item.description });
			cmd.Connection = _connection;
			_item.id = Convert.ToInt64(cmd.ExecuteScalar());
			m_Items.Add(_item.id, _item);
			_item.LoadAggregations(Meridian.Default);
			return _item;
		}
		public proto.seo_metadata Update(MySqlConnection _connection, proto.seo_metadata _item)
		{
			bool changed =  false;
			var cmdText =  "";
			var cmd = new MySqlCommand("UPDATE seo_metadata SET `entity_id`= @entity_id, `proto_name`= @proto_name, `url`= @url, `title`= @title, `keywords`= @keywords, `description`= @description WHERE id=@id"); ;
			if(_item.mc_id)
			{
			}
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "id", Value = _item.id });
			if(_item.mc_entity_id)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`entity_id` = @entity_id";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "entity_id", Value = _item.entity_id });
			}
			if(_item.mc_proto_name)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`proto_name` = @proto_name";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "proto_name", Value = _item.proto_name != null ? (object)_item.proto_name : DBNull.Value });
			}
			if(_item.mc_url)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`url` = @url";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "url", Value = _item.url != null ? (object)_item.url : DBNull.Value });
			}
			if(_item.mc_title)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`title` = @title";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "title", Value = _item.title != null ? (object)_item.title : DBNull.Value });
			}
			if(_item.mc_keywords)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`keywords` = @keywords";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "keywords", Value = _item.keywords != null ? (object)_item.keywords : DBNull.Value });
			}
			if(_item.mc_description)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`description` = @description";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "description", Value = _item.description != null ? (object)_item.description : DBNull.Value });
			}
			if(changed)
			{
				cmd.CommandText =  "UPDATE seo_metadata SET " + cmdText + " WHERE id=@id";
				cmd.Connection = _connection;
				cmd.ExecuteNonQuery();
				_item.LoadAggregations(Meridian.Default);
			}
			return _item;
		}
		public proto.seo_metadata Delete(MySqlConnection _connection, proto.seo_metadata _item)
		{
			var cmd = new MySqlCommand("DELETE FROM seo_metadata WHERE id=@id"); ;
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "id", Value = _item.id });
			cmd.Connection = _connection;
			cmd.ExecuteScalar();
			return _item;
		}
		public proto.seo_metadata Insert(proto.seo_metadata _item)
		{
			MeridianMonitor.Default.MySqlActionForeground((conn) => Insert(conn, _item));;
			return _item;
		}
		public proto.seo_metadata Persist(proto.seo_metadata _item)
		{
			if(_item.id <= 0)
			{
				_item = Insert(_item);
			}
			_item = Update(_item);
			return _item;
		}
		public proto.seo_metadata Delete(proto.seo_metadata _item)
		{
			_item.DeleteCompositions(Meridian.Default);
			_item.DeleteAggregations();
			m_Items.Remove(_item.id);
			MeridianMonitor.Default.MySqlActionBackground((conn) => Delete(conn, _item));;
			return _item;
		}
		public proto.seo_metadata Update(proto.seo_metadata _item)
		{
			MeridianMonitor.Default.MySqlActionBackground((conn) => Update(conn, _item));;
			return _item;
		}
		public IList<proto.seo_metadata> All()
		{
			return m_Items.Values;
		}
		public proto.seo_metadata Get(long _id)
		{
			return m_Items[_id];
		}
		public bool Exists(long _id)
		{
			return m_Items.ContainsKey(_id);
		}
		public void UpdateSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if (!Exists(_id))
			{
			return;
			}
			var item = Get(_id);
			var cmd = new MySqlCommand("SELECT `id`, `entity_id`, `proto_name`, `url`, `title`, `keywords`, `description` FROM seo_metadata WHERE id = " + _id.ToString());
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					item.DeleteCompositions(Meridian.Default);
					item.DeleteAggregations();
					item.LoadFromReader(reader);
					item.LoadAggregations(_meridian);
					item.LoadCompositions(_meridian);
				}
			}
		}
		public void InsertSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if(Exists(_id)) return;;
			var cmd = new MySqlCommand("SELECT `id`, `entity_id`, `proto_name`, `url`, `title`, `keywords`, `description` FROM seo_metadata WHERE id = " + _id.ToString());
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					var item = new proto.seo_metadata();
					item.LoadFromReader(reader);
					item.LoadAggregations(_meridian);
					item.LoadCompositions(_meridian);
					m_Items.Add(item.id, item);
				}
			}
		}
		public void DeleteSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if (!Exists(_id))
			{
			return;
			}
			var item = Get(_id);
			item.DeleteCompositions(Meridian.Default);
			item.DeleteAggregations();
			m_Items.Remove(item.id);
		}
	}
}
