/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;
using MySql.Data.MySqlClient;
using meridian.bewell;
using meridian.bewell.system;

namespace meridian.bewell.protoStore
{
	public partial class territoriesStore : Meridian.IEntityStore, admin.db.IDataService<proto.territories>
	{
		public territoriesStore()
		{
			m_Items = new SortedList<long, proto.territories>();
		}
		private SortedList<long, proto.territories> m_Items;
		public void Commit()
		{
			//throw new NotImplementedException();
		}
		public IQueryable<proto.territories> GetAll()
		{
			return Queryable.AsQueryable<proto.territories>(All());
		}
		public proto.territories GetById(long id)
		{
			return Get(id);
		}
		void admin.db.IDataService<proto.territories>.Insert(proto.territories item)
		{
			Insert(item);
		}
		void admin.db.IDataService<proto.territories>.Delete(proto.territories item)
		{
			Delete(item);
		}
		public proto.territories CreateItem()
		{
			return new proto.territories() {   };
		}
		public void AbortItem(proto.territories item)
		{
			Delete(item);
		}
		public void Discard()
		{
			;
		}
		void admin.db.IDataService<proto.territories>.Update(proto.territories item)
		{
			Persist(item);
		}
		public object GetObject(long _id)
		{
			return Get(_id);
		}
		public System.Type GetObjectType()
		{
			return typeof(proto.territories);
		}
		public void DeleteById(long _id)
		{
			Delete(Get(_id));
		}
		public void UpdateById(long _id)
		{
			Update(Get(_id));
		}
		public void LoadAggregations(Meridian _meridian)
		{
			foreach(var item in m_Items.Values)
			{
				item.LoadAggregations(_meridian);
			}
		}
		public void Select(MySqlConnection _connection)
		{
			var cmd = new MySqlCommand("SELECT `id`, `title`, `parent_id`, `category_id`, `nested_category_id`, `item_order`, `in_search`, `map_key` FROM territories");
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					var item = new proto.territories();
					item.LoadFromReader(reader);
					m_Items[item.id] = item;
				}
			}
		}
		public proto.territories Insert(MySqlConnection _connection, proto.territories _item)
		{
			var cmd = new MySqlCommand("INSERT INTO territories ( `title`, `parent_id`, `category_id`, `nested_category_id`, `item_order`, `in_search`, `map_key` ) VALUES ( @title, @parent_id, @category_id, @nested_category_id, @item_order, @in_search, @map_key ); SELECT LAST_INSERT_ID();"); ;
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "title", Value = _item.title });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "parent_id", Value = _item.parent_id });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "category_id", Value = _item.category_id });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "nested_category_id", Value = _item.nested_category_id });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "item_order", Value = _item.item_order });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "in_search", Value = _item.in_search });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "map_key", Value = _item.map_key });
			cmd.Connection = _connection;
			_item.id = Convert.ToInt64(cmd.ExecuteScalar());
			m_Items.Add(_item.id, _item);
			_item.LoadAggregations(Meridian.Default);
			return _item;
		}
		public proto.territories Update(MySqlConnection _connection, proto.territories _item)
		{
			bool changed =  false;
			var cmdText =  "";
			var cmd = new MySqlCommand("UPDATE territories SET `title`= @title, `parent_id`= @parent_id, `category_id`= @category_id, `nested_category_id`= @nested_category_id, `item_order`= @item_order, `in_search`= @in_search, `map_key`= @map_key WHERE id=@id"); ;
			if(_item.mc_id)
			{
			}
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "id", Value = _item.id });
			if(_item.mc_title)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`title` = @title";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "title", Value = _item.title != null ? (object)_item.title : DBNull.Value });
			}
			if(_item.mc_parent_id)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`parent_id` = @parent_id";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "parent_id", Value = _item.parent_id });
			}
			if(_item.mc_category_id)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`category_id` = @category_id";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "category_id", Value = _item.category_id });
			}
			if(_item.mc_nested_category_id)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`nested_category_id` = @nested_category_id";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "nested_category_id", Value = _item.nested_category_id });
			}
			if(_item.mc_item_order)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`item_order` = @item_order";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "item_order", Value = _item.item_order });
			}
			if(_item.mc_in_search)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`in_search` = @in_search";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "in_search", Value = _item.in_search });
			}
			if(_item.mc_map_key)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "`map_key` = @map_key";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "map_key", Value = _item.map_key != null ? (object)_item.map_key : DBNull.Value });
			}
			if(changed)
			{
				cmd.CommandText =  "UPDATE territories SET " + cmdText + " WHERE id=@id";
				cmd.Connection = _connection;
				cmd.ExecuteNonQuery();
				_item.LoadAggregations(Meridian.Default);
			}
			return _item;
		}
		public proto.territories Delete(MySqlConnection _connection, proto.territories _item)
		{
			var cmd = new MySqlCommand("DELETE FROM territories WHERE id=@id"); ;
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "id", Value = _item.id });
			cmd.Connection = _connection;
			cmd.ExecuteScalar();
			return _item;
		}
		public proto.territories Insert(proto.territories _item)
		{
			MeridianMonitor.Default.MySqlActionForeground((conn) => Insert(conn, _item));;
			return _item;
		}
		public proto.territories Persist(proto.territories _item)
		{
			if(_item.id <= 0)
			{
				_item = Insert(_item);
			}
			_item = Update(_item);
			return _item;
		}
		public proto.territories Delete(proto.territories _item)
		{
			_item.DeleteCompositions(Meridian.Default);
			_item.DeleteAggregations();
			m_Items.Remove(_item.id);
			MeridianMonitor.Default.MySqlActionBackground((conn) => Delete(conn, _item));;
			return _item;
		}
		public proto.territories Update(proto.territories _item)
		{
			MeridianMonitor.Default.MySqlActionBackground((conn) => Update(conn, _item));;
			return _item;
		}
		public IList<proto.territories> All()
		{
			return m_Items.Values;
		}
		public proto.territories Get(long _id)
		{
			return m_Items[_id];
		}
		public bool Exists(long _id)
		{
			return m_Items.ContainsKey(_id);
		}
		public void UpdateSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if (!Exists(_id))
			{
			return;
			}
			var item = Get(_id);
			var cmd = new MySqlCommand("SELECT `id`, `title`, `parent_id`, `category_id`, `nested_category_id`, `item_order`, `in_search`, `map_key` FROM territories WHERE id = " + _id.ToString());
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					item.DeleteCompositions(Meridian.Default);
					item.DeleteAggregations();
					item.LoadFromReader(reader);
					item.LoadAggregations(_meridian);
					item.LoadCompositions(_meridian);
				}
			}
		}
		public void InsertSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if(Exists(_id)) return;;
			var cmd = new MySqlCommand("SELECT `id`, `title`, `parent_id`, `category_id`, `nested_category_id`, `item_order`, `in_search`, `map_key` FROM territories WHERE id = " + _id.ToString());
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					var item = new proto.territories();
					item.LoadFromReader(reader);
					item.LoadAggregations(_meridian);
					item.LoadCompositions(_meridian);
					m_Items.Add(item.id, item);
				}
			}
		}
		public void DeleteSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if (!Exists(_id))
			{
			return;
			}
			var item = Get(_id);
			item.DeleteCompositions(Meridian.Default);
			item.DeleteAggregations();
			m_Items.Remove(item.id);
		}
	}
}
